from ChangeVolumeDialog import ChangeVolumeDialog
from ManualClassificationDialog import ManualClassificationDialog
from FilterDialog import FilterDialog
from InsertSilenceDialog import InsertSilenceDialog
from NewFileDialog import NewFileDialog
from SoundDevicesDialog import SoundDevicesDialog






