# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OptionsDialog.ui'
#
# Created: Thu Nov 07 12:59:47 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(462, 440)
        self.btonaceptar = QtGui.QPushButton(Dialog)
        self.btonaceptar.setGeometry(QtCore.QRect(20, 380, 81, 31))
        self.btonaceptar.setToolTip(_fromUtf8(""))
        self.btonaceptar.setCheckable(False)
        self.btonaceptar.setDefault(False)
        self.btonaceptar.setFlat(False)
        self.btonaceptar.setObjectName(_fromUtf8("btonaceptar"))
        self.btoncancelar = QtGui.QPushButton(Dialog)
        self.btoncancelar.setGeometry(QtCore.QRect(350, 380, 81, 31))
        self.btoncancelar.setToolTip(_fromUtf8(""))
        self.btoncancelar.setDefault(False)
        self.btoncancelar.setObjectName(_fromUtf8("btoncancelar"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 431, 311))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 411, 261))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.overlapspinbox = QtGui.QSpinBox(self.groupBox)
        self.overlapspinbox.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.overlapspinbox.setMinimum(1)
        self.overlapspinbox.setMaximum(99)
        self.overlapspinbox.setProperty("value", 50)
        self.overlapspinbox.setObjectName(_fromUtf8("overlapspinbox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(210, 70, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cboxwindowType = QtGui.QComboBox(self.groupBox)
        self.cboxwindowType.setGeometry(QtCore.QRect(210, 90, 141, 22))
        self.cboxwindowType.setEditable(False)
        self.cboxwindowType.setMaxVisibleItems(6)
        self.cboxwindowType.setMinimumContentsLength(1)
        self.cboxwindowType.setModelColumn(0)
        self.cboxwindowType.setObjectName(_fromUtf8("cboxwindowType"))
        self.cboxwindowType.addItem(_fromUtf8(""))
        self.cboxwindowType.addItem(_fromUtf8(""))
        self.cboxwindowType.addItem(_fromUtf8(""))
        self.cboxwindowType.addItem(_fromUtf8(""))
        self.cboxwindowType.addItem(_fromUtf8(""))
        self.cboxwindowType.addItem(_fromUtf8(""))
        self.cboxwindowType.addItem(_fromUtf8(""))
        self.cboxFFTNumber = QtGui.QComboBox(self.groupBox)
        self.cboxFFTNumber.setGeometry(QtCore.QRect(10, 30, 71, 22))
        self.cboxFFTNumber.setEditable(False)
        self.cboxFFTNumber.setMaxVisibleItems(6)
        self.cboxFFTNumber.setMinimumContentsLength(1)
        self.cboxFFTNumber.setModelColumn(0)
        self.cboxFFTNumber.setObjectName(_fromUtf8("cboxFFTNumber"))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.cboxFFTNumber.addItem(_fromUtf8(""))
        self.checkBoxOsgram = QtGui.QCheckBox(self.groupBox)
        self.checkBoxOsgram.setGeometry(QtCore.QRect(10, 120, 111, 17))
        self.checkBoxOsgram.setChecked(True)
        self.checkBoxOsgram.setObjectName(_fromUtf8("checkBoxOsgram"))
        self.checkBoxSpecgram = QtGui.QCheckBox(self.groupBox)
        self.checkBoxSpecgram.setGeometry(QtCore.QRect(10, 140, 121, 17))
        self.checkBoxSpecgram.setChecked(True)
        self.checkBoxSpecgram.setTristate(False)
        self.checkBoxSpecgram.setObjectName(_fromUtf8("checkBoxSpecgram"))
        self.checkBoxCursors = QtGui.QCheckBox(self.groupBox)
        self.checkBoxCursors.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.checkBoxCursors.setChecked(True)
        self.checkBoxCursors.setTristate(False)
        self.checkBoxCursors.setObjectName(_fromUtf8("checkBoxCursors"))
        self.cboxcolorpalette = QtGui.QComboBox(self.groupBox)
        self.cboxcolorpalette.setGeometry(QtCore.QRect(210, 200, 81, 22))
        self.cboxcolorpalette.setObjectName(_fromUtf8("cboxcolorpalette"))
        self.cboxcolorpalette.addItem(_fromUtf8(""))
        self.cboxcolorpalette.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(210, 176, 71, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(210, 20, 151, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.overlapspinboxthreshold = QtGui.QSpinBox(self.groupBox)
        self.overlapspinboxthreshold.setGeometry(QtCore.QRect(210, 40, 71, 21))
        self.overlapspinboxthreshold.setMinimum(0)
        self.overlapspinboxthreshold.setMaximum(100)
        self.overlapspinboxthreshold.setProperty("value", 50)
        self.overlapspinboxthreshold.setObjectName(_fromUtf8("overlapspinboxthreshold"))
        self.overlapspinboxthreshold_2 = QtGui.QSpinBox(self.groupBox)
        self.overlapspinboxthreshold_2.setGeometry(QtCore.QRect(210, 140, 71, 21))
        self.overlapspinboxthreshold_2.setMinimum(1)
        self.overlapspinboxthreshold_2.setMaximum(10000)
        self.overlapspinboxthreshold_2.setProperty("value", 100)
        self.overlapspinboxthreshold_2.setObjectName(_fromUtf8("overlapspinboxthreshold_2"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(210, 120, 151, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.checkBoxGrid = QtGui.QCheckBox(self.groupBox)
        self.checkBoxGrid.setGeometry(QtCore.QRect(10, 180, 121, 17))
        self.checkBoxGrid.setChecked(True)
        self.checkBoxGrid.setTristate(False)
        self.checkBoxGrid.setObjectName(_fromUtf8("checkBoxGrid"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.cboxFFTNumber.setCurrentIndex(0)
        QtCore.QObject.connect(self.btonaceptar, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.accept)
        QtCore.QObject.connect(self.btoncancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.btonaceptar.setText(_translate("Dialog", "Aceptar", None))
        self.btoncancelar.setText(_translate("Dialog", "Cancelar", None))
        self.label.setText(_translate("Dialog", "FFT Number", None))
        self.label_2.setText(_translate("Dialog", "Overlapping", None))
        self.label_3.setText(_translate("Dialog", "Window Type", None))
        self.cboxwindowType.setItemText(0, _translate("Dialog", "Hamming", None))
        self.cboxwindowType.setItemText(1, _translate("Dialog", "Rectangular", None))
        self.cboxwindowType.setItemText(2, _translate("Dialog", "Hanning", None))
        self.cboxwindowType.setItemText(3, _translate("Dialog", "Blackman", None))
        self.cboxwindowType.setItemText(4, _translate("Dialog", "Bartlett", None))
        self.cboxwindowType.setItemText(5, _translate("Dialog", "Kaiser", None))
        self.cboxwindowType.setItemText(6, _translate("Dialog", "None", None))
        self.cboxFFTNumber.setItemText(0, _translate("Dialog", "8192", None))
        self.cboxFFTNumber.setItemText(1, _translate("Dialog", "4096", None))
        self.cboxFFTNumber.setItemText(2, _translate("Dialog", "2048", None))
        self.cboxFFTNumber.setItemText(3, _translate("Dialog", "1024", None))
        self.cboxFFTNumber.setItemText(4, _translate("Dialog", "512", None))
        self.cboxFFTNumber.setItemText(5, _translate("Dialog", "256", None))
        self.cboxFFTNumber.setItemText(6, _translate("Dialog", "128", None))
        self.cboxFFTNumber.setItemText(7, _translate("Dialog", "64", None))
        self.cboxFFTNumber.setItemText(8, _translate("Dialog", "32", None))
        self.cboxFFTNumber.setItemText(9, _translate("Dialog", "16", None))
        self.cboxFFTNumber.setItemText(10, _translate("Dialog", "8", None))
        self.checkBoxOsgram.setText(_translate("Dialog", "Oscilogram Visible", None))
        self.checkBoxSpecgram.setText(_translate("Dialog", "Spectrogram Visible", None))
        self.checkBoxCursors.setText(_translate("Dialog", "Cursors Visibles", None))
        self.cboxcolorpalette.setItemText(0, _translate("Dialog", "GrayPalette", None))
        self.cboxcolorpalette.setItemText(1, _translate("Dialog", "ColorPalette", None))
        self.label_4.setText(_translate("Dialog", "Color Palette", None))
        self.label_5.setText(_translate("Dialog", "Threshold (Specgram Intensity)", None))
        self.label_6.setText(_translate("Dialog", "Sound Speed %", None))
        self.checkBoxGrid.setText(_translate("Dialog", "Grid", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Settings", None))

