# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ParameterMeasurementDialogUI.ui'
#
# Created: Tue Jan 21 19:51:31 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParameterMeasurement(object):
    def setupUi(self, ParameterMeasurement):
        ParameterMeasurement.setObjectName(_fromUtf8("ParameterMeasurement"))
        ParameterMeasurement.resize(542, 404)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParameterMeasurement.sizePolicy().hasHeightForWidth())
        ParameterMeasurement.setSizePolicy(sizePolicy)
        ParameterMeasurement.setSizeGripEnabled(False)
        self.verticalLayoutWidget = QtGui.QWidget(ParameterMeasurement)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 531, 381))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabOscParam = QtGui.QWidget()
        self.tabOscParam.setObjectName(_fromUtf8("tabOscParam"))
        self.gboxOscilogramParameters = QtGui.QGroupBox(self.tabOscParam)
        self.gboxOscilogramParameters.setGeometry(QtCore.QRect(10, 10, 501, 141))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gboxOscilogramParameters.sizePolicy().hasHeightForWidth())
        self.gboxOscilogramParameters.setSizePolicy(sizePolicy)
        self.gboxOscilogramParameters.setObjectName(_fromUtf8("gboxOscilogramParameters"))
        self.gridLayoutWidget = QtGui.QWidget(self.gboxOscilogramParameters)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 19, 481, 111))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.grdLyTemporalParameters = QtGui.QGridLayout(self.gridLayoutWidget)
        self.grdLyTemporalParameters.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.grdLyTemporalParameters.setMargin(0)
        self.grdLyTemporalParameters.setObjectName(_fromUtf8("grdLyTemporalParameters"))
        self.cbxDistancefromStartToMax = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cbxDistancefromStartToMax.setChecked(True)
        self.cbxDistancefromStartToMax.setObjectName(_fromUtf8("cbxDistancefromStartToMax"))
        self.grdLyTemporalParameters.addWidget(self.cbxDistancefromStartToMax, 2, 0, 1, 1)
        self.cbxEndTime = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cbxEndTime.setChecked(True)
        self.cbxEndTime.setObjectName(_fromUtf8("cbxEndTime"))
        self.grdLyTemporalParameters.addWidget(self.cbxEndTime, 1, 0, 1, 1)
        self.cbxStartTime_2 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cbxStartTime_2.setChecked(True)
        self.cbxStartTime_2.setObjectName(_fromUtf8("cbxStartTime_2"))
        self.grdLyTemporalParameters.addWidget(self.cbxStartTime_2, 0, 0, 1, 1)
        self.cbxRms = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cbxRms.setChecked(True)
        self.cbxRms.setObjectName(_fromUtf8("cbxRms"))
        self.grdLyTemporalParameters.addWidget(self.cbxRms, 0, 1, 1, 1)
        self.cbxPeekToPeek = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cbxPeekToPeek.setChecked(True)
        self.cbxPeekToPeek.setObjectName(_fromUtf8("cbxPeekToPeek"))
        self.grdLyTemporalParameters.addWidget(self.cbxPeekToPeek, 1, 1, 1, 1)
        self.cbxAbsMean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cbxAbsMean.setChecked(True)
        self.cbxAbsMean.setObjectName(_fromUtf8("cbxAbsMean"))
        self.grdLyTemporalParameters.addWidget(self.cbxAbsMean, 2, 1, 1, 1)
        self.gboxSpectralParameters = QtGui.QGroupBox(self.tabOscParam)
        self.gboxSpectralParameters.setGeometry(QtCore.QRect(10, 160, 501, 161))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gboxSpectralParameters.sizePolicy().hasHeightForWidth())
        self.gboxSpectralParameters.setSizePolicy(sizePolicy)
        self.gboxSpectralParameters.setObjectName(_fromUtf8("gboxSpectralParameters"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.gboxSpectralParameters)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 481, 121))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.grdLySpectralParameters = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.grdLySpectralParameters.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.grdLySpectralParameters.setMargin(0)
        self.grdLySpectralParameters.setObjectName(_fromUtf8("grdLySpectralParameters"))
        self.cbxPeakFrecuency = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbxPeakFrecuency.setChecked(True)
        self.cbxPeakFrecuency.setObjectName(_fromUtf8("cbxPeakFrecuency"))
        self.grdLySpectralParameters.addWidget(self.cbxPeakFrecuency, 2, 1, 1, 1)
        self.cbxquartiles = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbxquartiles.setChecked(True)
        self.cbxquartiles.setObjectName(_fromUtf8("cbxquartiles"))
        self.grdLySpectralParameters.addWidget(self.cbxquartiles, 0, 1, 1, 1)
        self.cbxMinFreq = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbxMinFreq.setChecked(True)
        self.cbxMinFreq.setObjectName(_fromUtf8("cbxMinFreq"))
        self.grdLySpectralParameters.addWidget(self.cbxMinFreq, 2, 0, 1, 1)
        self.cbxEndTime_2 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbxEndTime_2.setChecked(True)
        self.cbxEndTime_2.setObjectName(_fromUtf8("cbxEndTime_2"))
        self.grdLySpectralParameters.addWidget(self.cbxEndTime_2, 1, 0, 1, 1)
        self.cbxEntropy = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbxEntropy.setChecked(True)
        self.cbxEntropy.setObjectName(_fromUtf8("cbxEntropy"))
        self.grdLySpectralParameters.addWidget(self.cbxEntropy, 1, 1, 1, 1)
        self.cbxMaxFreq = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbxMaxFreq.setChecked(True)
        self.cbxMaxFreq.setObjectName(_fromUtf8("cbxMaxFreq"))
        self.grdLySpectralParameters.addWidget(self.cbxMaxFreq, 3, 0, 1, 1)
        self.cbxStartTime = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.cbxStartTime.setChecked(True)
        self.cbxStartTime.setObjectName(_fromUtf8("cbxStartTime"))
        self.grdLySpectralParameters.addWidget(self.cbxStartTime, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabOscParam, _fromUtf8(""))
        self.tabSpecParam = QtGui.QWidget()
        self.tabSpecParam.setObjectName(_fromUtf8("tabSpecParam"))
        self.tabWidget.addTab(self.tabSpecParam, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ParameterMeasurement)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ParameterMeasurement.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ParameterMeasurement.reject)
        QtCore.QMetaObject.connectSlotsByName(ParameterMeasurement)

    def retranslateUi(self, ParameterMeasurement):
        ParameterMeasurement.setWindowTitle(_translate("ParameterMeasurement", "Parameter Measurement", None))
        self.gboxOscilogramParameters.setTitle(_translate("ParameterMeasurement", "Temporal Parameters", None))
        self.cbxDistancefromStartToMax.setText(_translate("ParameterMeasurement", "Distance from start to max", None))
        self.cbxEndTime.setText(_translate("ParameterMeasurement", "End Time", None))
        self.cbxStartTime_2.setText(_translate("ParameterMeasurement", "Start Time", None))
        self.cbxRms.setText(_translate("ParameterMeasurement", "RMS", None))
        self.cbxPeekToPeek.setText(_translate("ParameterMeasurement", "Peek to Peek Amplitude", None))
        self.cbxAbsMean.setText(_translate("ParameterMeasurement", "Abs Mean", None))
        self.gboxSpectralParameters.setTitle(_translate("ParameterMeasurement", "Spectral Parameters", None))
        self.cbxPeakFrecuency.setText(_translate("ParameterMeasurement", "Peak Frecuency", None))
        self.cbxquartiles.setText(_translate("ParameterMeasurement", "Quartiles", None))
        self.cbxMinFreq.setText(_translate("ParameterMeasurement", "Min Freq", None))
        self.cbxEndTime_2.setText(_translate("ParameterMeasurement", "End Time", None))
        self.cbxEntropy.setText(_translate("ParameterMeasurement", "Entropy", None))
        self.cbxMaxFreq.setText(_translate("ParameterMeasurement", "Max Freq", None))
        self.cbxStartTime.setText(_translate("ParameterMeasurement", "Start Time", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOscParam), _translate("ParameterMeasurement", "Oscilogram Parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpecParam), _translate("ParameterMeasurement", "Specgram Parameters", None))

