# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Biologia\SISTEMA\DuettoSystem\Graphic_Interface\UI Files\ParameterMeasurementDialogUI.ui'
#
# Created: Mon Mar 31 14:33:29 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParameterMeasurement(object):
    def setupUi(self, ParameterMeasurement):
        ParameterMeasurement.setObjectName(_fromUtf8("ParameterMeasurement"))
        ParameterMeasurement.resize(342, 315)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParameterMeasurement.sizePolicy().hasHeightForWidth())
        ParameterMeasurement.setSizePolicy(sizePolicy)
        ParameterMeasurement.setSizeGripEnabled(False)
        self.gridLayout_3 = QtGui.QGridLayout(ParameterMeasurement)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gboxSpectral = QtGui.QGroupBox(ParameterMeasurement)
        self.gboxSpectral.setObjectName(_fromUtf8("gboxSpectral"))
        self.formLayout_2 = QtGui.QFormLayout(self.gboxSpectral)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.cbxDistancefromStartToMax_2 = QtGui.QCheckBox(self.gboxSpectral)
        self.cbxDistancefromStartToMax_2.setChecked(True)
        self.cbxDistancefromStartToMax_2.setObjectName(_fromUtf8("cbxDistancefromStartToMax_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.cbxDistancefromStartToMax_2)
        self.checkBox = QtGui.QCheckBox(self.gboxSpectral)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.gboxSpectral)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkBox_2)
        self.gridLayout_3.addWidget(self.gboxSpectral, 1, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(ParameterMeasurement)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.cbxmeasurementLocationStart = QtGui.QCheckBox(self.groupBox)
        self.cbxmeasurementLocationStart.setChecked(True)
        self.cbxmeasurementLocationStart.setObjectName(_fromUtf8("cbxmeasurementLocationStart"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.cbxmeasurementLocationStart)
        self.cbxmeasurementLocationCenter = QtGui.QCheckBox(self.groupBox)
        self.cbxmeasurementLocationCenter.setChecked(True)
        self.cbxmeasurementLocationCenter.setObjectName(_fromUtf8("cbxmeasurementLocationCenter"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.cbxmeasurementLocationCenter)
        self.cbxmeasurementLocationEnd = QtGui.QCheckBox(self.groupBox)
        self.cbxmeasurementLocationEnd.setChecked(True)
        self.cbxmeasurementLocationEnd.setObjectName(_fromUtf8("cbxmeasurementLocationEnd"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.cbxmeasurementLocationEnd)
        self.cbxmeasurementLocationQuartile25 = QtGui.QCheckBox(self.groupBox)
        self.cbxmeasurementLocationQuartile25.setChecked(True)
        self.cbxmeasurementLocationQuartile25.setObjectName(_fromUtf8("cbxmeasurementLocationQuartile25"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.cbxmeasurementLocationQuartile25)
        self.cbxmeasurementLocationQuartile75 = QtGui.QCheckBox(self.groupBox)
        self.cbxmeasurementLocationQuartile75.setChecked(True)
        self.cbxmeasurementLocationQuartile75.setObjectName(_fromUtf8("cbxmeasurementLocationQuartile75"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.cbxmeasurementLocationQuartile75)
        self.gridLayout_3.addWidget(self.groupBox, 1, 3, 1, 1)
        self.gboxOscilogramParameters = QtGui.QGroupBox(ParameterMeasurement)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gboxOscilogramParameters.sizePolicy().hasHeightForWidth())
        self.gboxOscilogramParameters.setSizePolicy(sizePolicy)
        self.gboxOscilogramParameters.setObjectName(_fromUtf8("gboxOscilogramParameters"))
        self.formLayout = QtGui.QFormLayout(self.gboxOscilogramParameters)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.cbxDuration = QtGui.QCheckBox(self.gboxOscilogramParameters)
        self.cbxDuration.setChecked(True)
        self.cbxDuration.setObjectName(_fromUtf8("cbxDuration"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.cbxDuration)
        self.cbxPeekToPeek = QtGui.QCheckBox(self.gboxOscilogramParameters)
        self.cbxPeekToPeek.setChecked(True)
        self.cbxPeekToPeek.setObjectName(_fromUtf8("cbxPeekToPeek"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbxPeekToPeek)
        self.cbxStartTime = QtGui.QCheckBox(self.gboxOscilogramParameters)
        self.cbxStartTime.setChecked(True)
        self.cbxStartTime.setObjectName(_fromUtf8("cbxStartTime"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.cbxStartTime)
        self.cbxEndTime = QtGui.QCheckBox(self.gboxOscilogramParameters)
        self.cbxEndTime.setChecked(True)
        self.cbxEndTime.setObjectName(_fromUtf8("cbxEndTime"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.cbxEndTime)
        self.cbxStartToMax = QtGui.QCheckBox(self.gboxOscilogramParameters)
        self.cbxStartToMax.setChecked(True)
        self.cbxStartToMax.setObjectName(_fromUtf8("cbxStartToMax"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.cbxStartToMax)
        self.cbxRms = QtGui.QCheckBox(self.gboxOscilogramParameters)
        self.cbxRms.setChecked(True)
        self.cbxRms.setObjectName(_fromUtf8("cbxRms"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbxRms)
        self.gridLayout_3.addWidget(self.gboxOscilogramParameters, 0, 2, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ParameterMeasurement)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 2, 2, 1, 2)

        self.retranslateUi(ParameterMeasurement)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ParameterMeasurement.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ParameterMeasurement.reject)
        QtCore.QMetaObject.connectSlotsByName(ParameterMeasurement)

    def retranslateUi(self, ParameterMeasurement):
        ParameterMeasurement.setWindowTitle(_translate("ParameterMeasurement", "Parameter Measurement", None))
        self.gboxSpectral.setTitle(_translate("ParameterMeasurement", "Spectral Parameters", None))
        self.cbxDistancefromStartToMax_2.setText(_translate("ParameterMeasurement", "Peak Frecuency(KHz)", None))
        self.checkBox.setText(_translate("ParameterMeasurement", "Max Frecuency (KHz)", None))
        self.checkBox_2.setText(_translate("ParameterMeasurement", "Min Frecuency (KHz)", None))
        self.groupBox.setTitle(_translate("ParameterMeasurement", "Measurement Location", None))
        self.cbxmeasurementLocationStart.setText(_translate("ParameterMeasurement", "Start", None))
        self.cbxmeasurementLocationCenter.setText(_translate("ParameterMeasurement", "Center", None))
        self.cbxmeasurementLocationEnd.setText(_translate("ParameterMeasurement", "End", None))
        self.cbxmeasurementLocationQuartile25.setText(_translate("ParameterMeasurement", "Quartile25", None))
        self.cbxmeasurementLocationQuartile75.setText(_translate("ParameterMeasurement", "Quartile75", None))
        self.gboxOscilogramParameters.setTitle(_translate("ParameterMeasurement", "Temporal Parameters", None))
        self.cbxDuration.setText(_translate("ParameterMeasurement", "Duration (ms)", None))
        self.cbxPeekToPeek.setText(_translate("ParameterMeasurement", "Peek to Peek", None))
        self.cbxStartTime.setText(_translate("ParameterMeasurement", "Start Time (ms)", None))
        self.cbxEndTime.setText(_translate("ParameterMeasurement", "End Time (ms)", None))
        self.cbxStartToMax.setText(_translate("ParameterMeasurement", "Start To Max (ms)", None))
        self.cbxRms.setText(_translate("ParameterMeasurement", "RMS", None))