# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Biologia\SISTEMA\DuettoSystemYasel\Graphic_Interface\UI Files\ui_elemDetectSettings.ui'
#
# Created: Mon Mar 24 21:22:49 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(919, 371)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.dockWidget = QtGui.QDockWidget(self.groupBox_2)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chbxDetectOsc = QtGui.QCheckBox(self.dockWidgetContents_2)
        self.chbxDetectOsc.setChecked(True)
        self.chbxDetectOsc.setObjectName(_fromUtf8("chbxDetectOsc"))
        self.verticalLayout.addWidget(self.chbxDetectOsc)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.dsbxThreshold = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.dsbxThreshold.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dsbxThreshold.setMinimum(-60.0)
        self.dsbxThreshold.setMaximum(0.0)
        self.dsbxThreshold.setObjectName(_fromUtf8("dsbxThreshold"))
        self.horizontalLayout_7.addWidget(self.dsbxThreshold)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.dsbxThreshold2 = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.dsbxThreshold2.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dsbxThreshold2.setMinimum(-60.0)
        self.dsbxThreshold2.setMaximum(0.0)
        self.dsbxThreshold2.setProperty("value", 0.0)
        self.dsbxThreshold2.setObjectName(_fromUtf8("dsbxThreshold2"))
        self.horizontalLayout_11.addWidget(self.dsbxThreshold2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.dsbxDecay = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.dsbxDecay.setObjectName(_fromUtf8("dsbxDecay"))
        self.horizontalLayout_5.addWidget(self.dsbxDecay)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.dsbxMinSize = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.dsbxMinSize.setObjectName(_fromUtf8("dsbxMinSize"))
        self.horizontalLayout_3.addWidget(self.dsbxMinSize)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.sbxSoftFactor = QtGui.QSpinBox(self.dockWidgetContents_2)
        self.sbxSoftFactor.setMinimum(2)
        self.sbxSoftFactor.setMaximum(10)
        self.sbxSoftFactor.setSingleStep(2)
        self.sbxSoftFactor.setProperty("value", 6)
        self.sbxSoftFactor.setObjectName(_fromUtf8("sbxSoftFactor"))
        self.horizontalLayout_6.addWidget(self.sbxSoftFactor)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.dsbxMergeFactor = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.dsbxMergeFactor.setObjectName(_fromUtf8("dsbxMergeFactor"))
        self.horizontalLayout_4.addWidget(self.dsbxMergeFactor)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        self.gridLayout_2.addWidget(self.dockWidget, 0, 0, 1, 1)
        self.dockWidget_2 = QtGui.QDockWidget(self.groupBox_2)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chbxDetectSpec = QtGui.QCheckBox(self.dockWidgetContents_3)
        self.chbxDetectSpec.setChecked(True)
        self.chbxDetectSpec.setTristate(False)
        self.chbxDetectSpec.setObjectName(_fromUtf8("chbxDetectSpec"))
        self.gridLayout_3.addWidget(self.chbxDetectSpec, 0, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.sbxMergeFactorTime = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.sbxMergeFactorTime.setEnabled(True)
        self.sbxMergeFactorTime.setObjectName(_fromUtf8("sbxMergeFactorTime"))
        self.horizontalLayout_10.addWidget(self.sbxMergeFactorTime)
        self.sbxMergeFactorFreq = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.sbxMergeFactorFreq.setEnabled(True)
        self.sbxMergeFactorFreq.setObjectName(_fromUtf8("sbxMergeFactorFreq"))
        self.horizontalLayout_10.addWidget(self.sbxMergeFactorFreq)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.dsbxminSizeTime = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.dsbxminSizeTime.setEnabled(True)
        self.dsbxminSizeTime.setObjectName(_fromUtf8("dsbxminSizeTime"))
        self.horizontalLayout_8.addWidget(self.dsbxminSizeTime)
        self.dsbxMinSizeFreq = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.dsbxMinSizeFreq.setEnabled(True)
        self.dsbxMinSizeFreq.setObjectName(_fromUtf8("dsbxMinSizeFreq"))
        self.horizontalLayout_8.addWidget(self.dsbxMinSizeFreq)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.dsbxThresholdSpec = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.dsbxThresholdSpec.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbxThresholdSpec.sizePolicy().hasHeightForWidth())
        self.dsbxThresholdSpec.setSizePolicy(sizePolicy)
        self.dsbxThresholdSpec.setWrapping(False)
        self.dsbxThresholdSpec.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dsbxThresholdSpec.setMinimum(1.0)
        self.dsbxThresholdSpec.setSingleStep(5.0)
        self.dsbxThresholdSpec.setProperty("value", 95.0)
        self.dsbxThresholdSpec.setObjectName(_fromUtf8("dsbxThresholdSpec"))
        self.horizontalLayout_9.addWidget(self.dsbxThresholdSpec)
        self.horizontalLayout_9.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 1, 1, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_3)
        self.gridLayout_2.addWidget(self.dockWidget_2, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.groupBox_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.widget = QSignalVisualizerWidget(Dialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Detection Settings", None))
        self.dockWidget.setWindowTitle(_translate("Dialog", "Oscilogram ", None))
        self.chbxDetectOsc.setText(_translate("Dialog", "Detect elements in oscillogram", None))
        self.label_6.setText(_translate("Dialog", "Threshold:", None))
        self.dsbxThreshold.setSuffix(_translate("Dialog", "dB", None))
        self.label_10.setText(_translate("Dialog", "Threshold 2:", None))
        self.dsbxThreshold2.setSuffix(_translate("Dialog", "dB", None))
        self.label_4.setText(_translate("Dialog", "Decay:", None))
        self.dsbxDecay.setSuffix(_translate("Dialog", " ms", None))
        self.label_2.setText(_translate("Dialog", "Minimum size:", None))
        self.dsbxMinSize.setSuffix(_translate("Dialog", " ms", None))
        self.label_5.setText(_translate("Dialog", "Soft factor:", None))
        self.label_3.setText(_translate("Dialog", "Merge factor:", None))
        self.dsbxMergeFactor.setSuffix(_translate("Dialog", " ms", None))
        self.dockWidget_2.setWindowTitle(_translate("Dialog", "Espectrogram", None))
        self.chbxDetectSpec.setText(_translate("Dialog", "Detect elements in spectrogram", None))
        self.label_9.setText(_translate("Dialog", "Merge factor:", None))
        self.sbxMergeFactorTime.setSuffix(_translate("Dialog", " ms", None))
        self.sbxMergeFactorFreq.setSuffix(_translate("Dialog", " kHz", None))
        self.label_7.setText(_translate("Dialog", "Minimum size:", None))
        self.dsbxminSizeTime.setSuffix(_translate("Dialog", " ms", None))
        self.dsbxMinSizeFreq.setSuffix(_translate("Dialog", " kHz", None))
        self.label_8.setText(_translate("Dialog", "Threshold:", None))
        self.dsbxThresholdSpec.setSuffix(_translate("Dialog", "%", None))

from Graphic_Interface.Widgets.QSignalVisualizerWidget import QSignalVisualizerWidget
