# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Gaby\Desktop\DuettoSystem\Graphic_Interface\UI Files\MainWindow.ui'
#
# Created: Wed Mar 19 10:05:59 2014
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DuettoMainWindow(object):
    def setupUi(self, DuettoMainWindow):
        DuettoMainWindow.setObjectName(_fromUtf8("DuettoMainWindow"))
        DuettoMainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        DuettoMainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DuettoMainWindow.sizePolicy().hasHeightForWidth())
        DuettoMainWindow.setSizePolicy(sizePolicy)
        DuettoMainWindow.setAutoFillBackground(False)
        DuettoMainWindow.setStyleSheet(_fromUtf8("font: 10pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"padding:1%;"))
        self.centralwidget = QtGui.QWidget(DuettoMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget = QSignalVisualizerWidget(self.centralwidget)
        self.widget.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.136364 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.verticalLayout_2.addWidget(self.horizontalScrollBar)
        DuettoMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DuettoMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet(_fromUtf8("background-color:rgb(109, 152, 165);\n"
"alternate-background-color: rgb(109, 152, 165);\n"
""))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setStyleSheet(_fromUtf8("background-color: rgb(174, 200, 255);\n"
"selection-background-color:rgb(170, 170, 255)"))
        self.menuFile.setTearOffEnabled(False)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setStyleSheet(_fromUtf8("background-color:rgb(174, 200, 255);\n"
"selection-background-color:rgb(170, 170, 255)"))
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setStyleSheet(_fromUtf8("background-color: rgb(174, 200, 255);\n"
"selection-background-color:rgb(170, 170, 255)"))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuGenerate = QtGui.QMenu(self.menuEdit)
        self.menuGenerate.setObjectName(_fromUtf8("menuGenerate"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setStyleSheet(_fromUtf8("background-color:rgb(174, 200, 255);\n"
"selection-background-color:rgb(170, 170, 255)"))
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuSound = QtGui.QMenu(self.menubar)
        self.menuSound.setStyleSheet(_fromUtf8("background-color:rgb(174, 200, 255);\n"
"selection-background-color:rgb(170, 170, 255)"))
        self.menuSound.setObjectName(_fromUtf8("menuSound"))
        self.menuView_2 = QtGui.QMenu(self.menubar)
        self.menuView_2.setStyleSheet(_fromUtf8("background-color: rgb(174, 200, 255);\n"
"selection-background-color:rgb(170, 170, 255)"))
        self.menuView_2.setObjectName(_fromUtf8("menuView_2"))
        DuettoMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DuettoMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DuettoMainWindow.setStatusBar(self.statusbar)
        self.dock_settings = QtGui.QDockWidget(DuettoMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_settings.sizePolicy().hasHeightForWidth())
        self.dock_settings.setSizePolicy(sizePolicy)
        self.dock_settings.setMinimumSize(QtCore.QSize(250, 40))
        self.dock_settings.setMaximumSize(QtCore.QSize(250, 524287))
        self.dock_settings.setStyleSheet(_fromUtf8(""))
        self.dock_settings.setFloating(True)
        self.dock_settings.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dock_settings.setObjectName(_fromUtf8("dock_settings"))
        self.osc_settings_contents = QtGui.QWidget()
        self.osc_settings_contents.setObjectName(_fromUtf8("osc_settings_contents"))
        self.dock_settings.setWidget(self.osc_settings_contents)
        DuettoMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_settings)
        self.toolBar = QtGui.QToolBar(DuettoMainWindow)
        self.toolBar.setStyleSheet(_fromUtf8("background-color:rgb(109, 152, 165);\n"
"border-color: rgb(170, 170, 255);"))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DuettoMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(DuettoMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/81.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(DuettoMainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionZoomIn = QtGui.QAction(DuettoMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoomin_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon1)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoom_out = QtGui.QAction(DuettoMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoomout_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon2)
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.actionSelect_all = QtGui.QAction(DuettoMainWindow)
        self.actionSelect_all.setObjectName(_fromUtf8("actionSelect_all"))
        self.actionSpectogram = QtGui.QAction(DuettoMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/spec.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpectogram.setIcon(icon3)
        self.actionSpectogram.setObjectName(_fromUtf8("actionSpectogram"))
        self.actionOscilogram = QtGui.QAction(DuettoMainWindow)
        self.actionOscilogram.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/osc.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOscilogram.setIcon(icon4)
        self.actionOscilogram.setVisible(True)
        self.actionOscilogram.setObjectName(_fromUtf8("actionOscilogram"))
        self.actionCombined = QtGui.QAction(DuettoMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/combined.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCombined.setIcon(icon5)
        self.actionCombined.setObjectName(_fromUtf8("actionCombined"))
        self.actionNew = QtGui.QAction(DuettoMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/Leopard Icon 60.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon6)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionPower_Spectrum = QtGui.QAction(DuettoMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/powerspec.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPower_Spectrum.setIcon(icon7)
        self.actionPower_Spectrum.setObjectName(_fromUtf8("actionPower_Spectrum"))
        self.actionOscillogram_Settings = QtGui.QAction(DuettoMainWindow)
        self.actionOscillogram_Settings.setObjectName(_fromUtf8("actionOscillogram_Settings"))
        self.actionSpectogram_Settings = QtGui.QAction(DuettoMainWindow)
        self.actionSpectogram_Settings.setObjectName(_fromUtf8("actionSpectogram_Settings"))
        self.actionPower_Spectrum_Settings = QtGui.QAction(DuettoMainWindow)
        self.actionPower_Spectrum_Settings.setObjectName(_fromUtf8("actionPower_Spectrum_Settings"))
        self.actionPlay_Sound = QtGui.QAction(DuettoMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02049_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay_Sound.setIcon(icon8)
        self.actionPlay_Sound.setObjectName(_fromUtf8("actionPlay_Sound"))
        self.actionStop_Sound = QtGui.QAction(DuettoMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02051_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop_Sound.setIcon(icon9)
        self.actionStop_Sound.setObjectName(_fromUtf8("actionStop_Sound"))
        self.actionPause_Sound = QtGui.QAction(DuettoMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/pausa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause_Sound.setIcon(icon10)
        self.actionPause_Sound.setObjectName(_fromUtf8("actionPause_Sound"))
        self.actionZoom_out_entire_file = QtGui.QAction(DuettoMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoom_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out_entire_file.setIcon(icon11)
        self.actionZoom_out_entire_file.setObjectName(_fromUtf8("actionZoom_out_entire_file"))
        self.actionSave = QtGui.QAction(DuettoMainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/225.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon12)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionCopy = QtGui.QAction(DuettoMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/copy_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon13)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(DuettoMainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/paste_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon14)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionCut = QtGui.QAction(DuettoMainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/cut_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon15)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionHighest_frecuency = QtGui.QAction(DuettoMainWindow)
        self.actionHighest_frecuency.setCheckable(False)
        self.actionHighest_frecuency.setEnabled(True)
        self.actionHighest_frecuency.setObjectName(_fromUtf8("actionHighest_frecuency"))
        self.actionHighest_instant_frequency = QtGui.QAction(DuettoMainWindow)
        self.actionHighest_instant_frequency.setCheckable(False)
        self.actionHighest_instant_frequency.setObjectName(_fromUtf8("actionHighest_instant_frequency"))
        self.actionClear_Spectogram = QtGui.QAction(DuettoMainWindow)
        self.actionClear_Spectogram.setObjectName(_fromUtf8("actionClear_Spectogram"))
        self.actionSettings = QtGui.QAction(DuettoMainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/LeopardVista V4 Icon 09.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon16)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionRecord = QtGui.QAction(DuettoMainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/record_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon17)
        self.actionRecord.setObjectName(_fromUtf8("actionRecord"))
        self.action_Reverse = QtGui.QAction(DuettoMainWindow)
        self.action_Reverse.setObjectName(_fromUtf8("action_Reverse"))
        self.actionInsert_Silence = QtGui.QAction(DuettoMainWindow)
        self.actionInsert_Silence.setObjectName(_fromUtf8("actionInsert_Silence"))
        self.actionSilence = QtGui.QAction(DuettoMainWindow)
        self.actionSilence.setObjectName(_fromUtf8("actionSilence"))
        self.actionFilter = QtGui.QAction(DuettoMainWindow)
        self.actionFilter.setObjectName(_fromUtf8("actionFilter"))
        self.actionSmart_Scale = QtGui.QAction(DuettoMainWindow)
        self.actionSmart_Scale.setObjectName(_fromUtf8("actionSmart_Scale"))
        self.actionNormalize = QtGui.QAction(DuettoMainWindow)
        self.actionNormalize.setObjectName(_fromUtf8("actionNormalize"))
        self.actionResampling = QtGui.QAction(DuettoMainWindow)
        self.actionResampling.setObjectName(_fromUtf8("actionResampling"))
        self.actionGenerate_White_Noise = QtGui.QAction(DuettoMainWindow)
        self.actionGenerate_White_Noise.setObjectName(_fromUtf8("actionGenerate_White_Noise"))
        self.actionSegmentation_And_Clasification = QtGui.QAction(DuettoMainWindow)
        self.actionSegmentation_And_Clasification.setObjectName(_fromUtf8("actionSegmentation_And_Clasification"))
        self.actionEnvelope = QtGui.QAction(DuettoMainWindow)
        self.actionEnvelope.setObjectName(_fromUtf8("actionEnvelope"))
        self.actionGenerate_Pink_Noise = QtGui.QAction(DuettoMainWindow)
        self.actionGenerate_Pink_Noise.setObjectName(_fromUtf8("actionGenerate_Pink_Noise"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionZoomIn)
        self.menuTools.addAction(self.actionZoom_out)
        self.menuTools.addAction(self.actionZoom_out_entire_file)
        self.menuGenerate.addAction(self.actionGenerate_White_Noise)
        self.menuGenerate.addAction(self.actionGenerate_Pink_Noise)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_all)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.action_Reverse)
        self.menuEdit.addAction(self.actionInsert_Silence)
        self.menuEdit.addAction(self.actionSilence)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFilter)
        self.menuEdit.addAction(self.actionSmart_Scale)
        self.menuEdit.addAction(self.actionNormalize)
        self.menuEdit.addAction(self.actionResampling)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuGenerate.menuAction())
        self.menuView.addAction(self.actionOscilogram)
        self.menuView.addAction(self.actionSpectogram)
        self.menuView.addAction(self.actionCombined)
        self.menuView.addAction(self.actionPower_Spectrum)
        self.menuView.addAction(self.actionEnvelope)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionSettings)
        self.menuSound.addAction(self.actionPlay_Sound)
        self.menuSound.addAction(self.actionStop_Sound)
        self.menuSound.addAction(self.actionPause_Sound)
        self.menuSound.addAction(self.actionRecord)
        self.menuView_2.addAction(self.actionHighest_instant_frequency)
        self.menuView_2.addAction(self.actionClear_Spectogram)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSound.menuAction())
        self.menubar.addAction(self.menuView_2.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRecord)
        self.toolBar.addAction(self.actionPause_Sound)
        self.toolBar.addAction(self.actionPlay_Sound)
        self.toolBar.addAction(self.actionStop_Sound)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addAction(self.actionZoom_out_entire_file)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCombined)
        self.toolBar.addAction(self.actionOscilogram)
        self.toolBar.addAction(self.actionSpectogram)
        self.toolBar.addAction(self.actionPower_Spectrum)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionSegmentation_And_Clasification)

        self.retranslateUi(DuettoMainWindow)
        QtCore.QMetaObject.connectSlotsByName(DuettoMainWindow)

    def retranslateUi(self, DuettoMainWindow):
        DuettoMainWindow.setWindowTitle(QtGui.QApplication.translate("DuettoMainWindow", "Duetto Sound Lab", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGenerate.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSound.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView_2.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_settings.setWindowTitle(QtGui.QApplication.translate("DuettoMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("DuettoMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("DuettoMainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("DuettoMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("DuettoMainWindow", "Zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setText(QtGui.QApplication.translate("DuettoMainWindow", "Zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_all.setText(QtGui.QApplication.translate("DuettoMainWindow", "Select all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpectogram.setText(QtGui.QApplication.translate("DuettoMainWindow", "Spectogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOscilogram.setText(QtGui.QApplication.translate("DuettoMainWindow", "Oscillogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCombined.setText(QtGui.QApplication.translate("DuettoMainWindow", "Combined", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("DuettoMainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPower_Spectrum.setText(QtGui.QApplication.translate("DuettoMainWindow", "Power Spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOscillogram_Settings.setText(QtGui.QApplication.translate("DuettoMainWindow", "Oscillogram Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpectogram_Settings.setText(QtGui.QApplication.translate("DuettoMainWindow", "Spectrogram Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPower_Spectrum_Settings.setText(QtGui.QApplication.translate("DuettoMainWindow", "Power Spectrum Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Sound.setText(QtGui.QApplication.translate("DuettoMainWindow", "Play Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Sound.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Sound.setText(QtGui.QApplication.translate("DuettoMainWindow", "Stop Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause_Sound.setText(QtGui.QApplication.translate("DuettoMainWindow", "Pause Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out_entire_file.setText(QtGui.QApplication.translate("DuettoMainWindow", "Zoom out entire file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("DuettoMainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("DuettoMainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("DuettoMainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("DuettoMainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHighest_frecuency.setText(QtGui.QApplication.translate("DuettoMainWindow", "Highest frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHighest_instant_frequency.setText(QtGui.QApplication.translate("DuettoMainWindow", "Highest instant frequency ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Spectogram.setText(QtGui.QApplication.translate("DuettoMainWindow", "Clear Spectrogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("DuettoMainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecord.setText(QtGui.QApplication.translate("DuettoMainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Reverse.setText(QtGui.QApplication.translate("DuettoMainWindow", "Reverse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInsert_Silence.setText(QtGui.QApplication.translate("DuettoMainWindow", "Insert Silence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSilence.setText(QtGui.QApplication.translate("DuettoMainWindow", "Silence", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilter.setText(QtGui.QApplication.translate("DuettoMainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSmart_Scale.setText(QtGui.QApplication.translate("DuettoMainWindow", "Smart Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormalize.setText(QtGui.QApplication.translate("DuettoMainWindow", "Normalize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResampling.setText(QtGui.QApplication.translate("DuettoMainWindow", "Resampling", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_White_Noise.setText(QtGui.QApplication.translate("DuettoMainWindow", "White Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSegmentation_And_Clasification.setText(QtGui.QApplication.translate("DuettoMainWindow", "Segmentation And Clasification", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnvelope.setText(QtGui.QApplication.translate("DuettoMainWindow", "Envelope", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate_Pink_Noise.setText(QtGui.QApplication.translate("DuettoMainWindow", "Pink Noise", None, QtGui.QApplication.UnicodeUTF8))

from Graphic_Interface.Widgets.QSignalVisualizerWidget import QSignalVisualizerWidget
import icons_rc
