# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Biologia\SISTEMA\DuettoSystemYasel\Graphic_Interface\UI Files\SegmentationAndClasificationWindowUI.ui'
#
# Created: Tue Mar 18 10:20:13 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(769, 562)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("font: 10pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"padding:1%;"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabwidget = QtGui.QTabWidget(self.centralwidget)
        self.tabwidget.setStyleSheet(_fromUtf8(""))
        self.tabwidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabwidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabwidget.setUsesScrollButtons(True)
        self.tabwidget.setTabsClosable(False)
        self.tabwidget.setMovable(True)
        self.tabwidget.setObjectName(_fromUtf8("tabwidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QSignalVisualizerWidget(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.tabwidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listwidgetProgress = QtGui.QListWidget(self.tab_2)
        self.listwidgetProgress.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.listwidgetProgress.setObjectName(_fromUtf8("listwidgetProgress"))
        self.gridLayout_4.addWidget(self.listwidgetProgress, 3, 0, 1, 1)
        self.pushButtonInputFolder = QtGui.QPushButton(self.tab_2)
        self.pushButtonInputFolder.setFlat(False)
        self.pushButtonInputFolder.setObjectName(_fromUtf8("pushButtonInputFolder"))
        self.gridLayout_4.addWidget(self.pushButtonInputFolder, 0, 1, 1, 1)
        self.progressBarProcesed = QtGui.QProgressBar(self.tab_2)
        self.progressBarProcesed.setProperty("value", 0)
        self.progressBarProcesed.setObjectName(_fromUtf8("progressBarProcesed"))
        self.gridLayout_4.addWidget(self.progressBarProcesed, 4, 0, 1, 1)
        self.lineEditOutputFolder = QtGui.QLineEdit(self.tab_2)
        self.lineEditOutputFolder.setObjectName(_fromUtf8("lineEditOutputFolder"))
        self.gridLayout_4.addWidget(self.lineEditOutputFolder, 1, 0, 1, 1)
        self.pushButtonStart = QtGui.QPushButton(self.tab_2)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.gridLayout_4.addWidget(self.pushButtonStart, 0, 2, 1, 1)
        self.lineeditFilePath = QtGui.QLineEdit(self.tab_2)
        self.lineeditFilePath.setObjectName(_fromUtf8("lineeditFilePath"))
        self.gridLayout_4.addWidget(self.lineeditFilePath, 0, 0, 1, 1)
        self.pushButtonOutputFolder = QtGui.QPushButton(self.tab_2)
        self.pushButtonOutputFolder.setObjectName(_fromUtf8("pushButtonOutputFolder"))
        self.gridLayout_4.addWidget(self.pushButtonOutputFolder, 1, 1, 1, 1)
        self.cbxSingleFile = QtGui.QCheckBox(self.tab_2)
        self.cbxSingleFile.setObjectName(_fromUtf8("cbxSingleFile"))
        self.gridLayout_4.addWidget(self.cbxSingleFile, 1, 2, 1, 1)
        self.tabwidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabwidget)
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.verticalLayout_2.addWidget(self.horizontalScrollBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setStyleSheet(_fromUtf8("background-color:rgb(109, 152, 165);\n"
"border-color: rgb(170, 170, 255);"))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetParameterTableOscilogram = QtGui.QDockWidget(MainWindow)
        self.dockWidgetParameterTableOscilogram.setObjectName(_fromUtf8("dockWidgetParameterTableOscilogram"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableParameterOscilogram = QtGui.QTableWidget(self.dockWidgetContents)
        self.tableParameterOscilogram.setObjectName(_fromUtf8("tableParameterOscilogram"))
        self.tableParameterOscilogram.setColumnCount(0)
        self.tableParameterOscilogram.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableParameterOscilogram)
        self.dockWidgetParameterTableOscilogram.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetParameterTableOscilogram)
        self.dockWidgetParameterTableSpectrogram = QtGui.QDockWidget(MainWindow)
        self.dockWidgetParameterTableSpectrogram.setObjectName(_fromUtf8("dockWidgetParameterTableSpectrogram"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableParameterSpectrogram = QtGui.QTableWidget(self.dockWidgetContents_2)
        self.tableParameterSpectrogram.setObjectName(_fromUtf8("tableParameterSpectrogram"))
        self.tableParameterSpectrogram.setColumnCount(0)
        self.tableParameterSpectrogram.setRowCount(0)
        self.verticalLayout.addWidget(self.tableParameterSpectrogram)
        self.dockWidgetParameterTableSpectrogram.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetParameterTableSpectrogram)
        self.dock_settings = QtGui.QDockWidget(MainWindow)
        self.dock_settings.setObjectName(_fromUtf8("dock_settings"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.osc_settings_contents = QtGui.QWidget(self.dockWidgetContents_5)
        self.osc_settings_contents.setObjectName(_fromUtf8("osc_settings_contents"))
        self.gridLayout_2.addWidget(self.osc_settings_contents, 0, 0, 1, 1)
        self.dock_settings.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_settings)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 769, 24))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuExport = QtGui.QMenu(self.menuBar)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuParameters = QtGui.QMenu(self.menuBar)
        self.menuParameters.setObjectName(_fromUtf8("menuParameters"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionZoomIn = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoomin_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoom_out = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoomout_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon1)
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.actionSelect_all = QtGui.QAction(MainWindow)
        self.actionSelect_all.setObjectName(_fromUtf8("actionSelect_all"))
        self.actionSpectogram = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/spec.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpectogram.setIcon(icon2)
        self.actionSpectogram.setObjectName(_fromUtf8("actionSpectogram"))
        self.actionOscilogram = QtGui.QAction(MainWindow)
        self.actionOscilogram.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/osc.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOscilogram.setIcon(icon3)
        self.actionOscilogram.setVisible(True)
        self.actionOscilogram.setObjectName(_fromUtf8("actionOscilogram"))
        self.actionCombined = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/combined.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCombined.setIcon(icon4)
        self.actionCombined.setObjectName(_fromUtf8("actionCombined"))
        self.actionOscillogram_Settings = QtGui.QAction(MainWindow)
        self.actionOscillogram_Settings.setObjectName(_fromUtf8("actionOscillogram_Settings"))
        self.actionSpectogram_Settings = QtGui.QAction(MainWindow)
        self.actionSpectogram_Settings.setObjectName(_fromUtf8("actionSpectogram_Settings"))
        self.actionPlay_Sound = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02049_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay_Sound.setIcon(icon5)
        self.actionPlay_Sound.setObjectName(_fromUtf8("actionPlay_Sound"))
        self.actionStop_Sound = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02051_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop_Sound.setIcon(icon6)
        self.actionStop_Sound.setObjectName(_fromUtf8("actionStop_Sound"))
        self.actionPause_Sound = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause_Sound.setIcon(icon7)
        self.actionPause_Sound.setObjectName(_fromUtf8("actionPause_Sound"))
        self.actionZoom_out_entire_file = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoom_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out_entire_file.setIcon(icon8)
        self.actionZoom_out_entire_file.setObjectName(_fromUtf8("actionZoom_out_entire_file"))
        self.actionCopy = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/copy_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon9)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/paste_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon10)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionCut = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/cut_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon11)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/LeopardVista V4 Icon 09.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon12)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionExcel_File = QtGui.QAction(MainWindow)
        self.actionExcel_File.setObjectName(_fromUtf8("actionExcel_File"))
        self.actionView_Parameters = QtGui.QAction(MainWindow)
        self.actionView_Parameters.setObjectName(_fromUtf8("actionView_Parameters"))
        self.actionParameters_Measurement = QtGui.QAction(MainWindow)
        self.actionParameters_Measurement.setObjectName(_fromUtf8("actionParameters_Measurement"))
        self.actionDetection = QtGui.QAction(MainWindow)
        self.actionDetection.setObjectName(_fromUtf8("actionDetection"))
        self.actionClear_Meditions = QtGui.QAction(MainWindow)
        self.actionClear_Meditions.setObjectName(_fromUtf8("actionClear_Meditions"))
        self.toolBar.addAction(self.actionPlay_Sound)
        self.toolBar.addAction(self.actionPause_Sound)
        self.toolBar.addAction(self.actionStop_Sound)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addAction(self.actionZoom_out_entire_file)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCombined)
        self.toolBar.addAction(self.actionOscilogram)
        self.toolBar.addAction(self.actionSpectogram)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionDetection)
        self.toolBar.addAction(self.actionSelect_all)
        self.menuExport.addAction(self.actionExcel_File)
        self.menuParameters.addAction(self.actionView_Parameters)
        self.menuParameters.addAction(self.actionParameters_Measurement)
        self.menuParameters.addAction(self.actionClear_Meditions)
        self.menuBar.addAction(self.menuExport.menuAction())
        self.menuBar.addAction(self.menuParameters.menuAction())

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButtonInputFolder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.selectInputFolder)
        QtCore.QObject.connect(self.pushButtonOutputFolder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.selectOutputFolder)
        QtCore.QObject.connect(self.pushButtonStart, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.startBatchProcess)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Duetto Sound Lab", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab), _translate("MainWindow", "Detection", None))
        self.pushButtonInputFolder.setText(_translate("MainWindow", "Explore", None))
        self.lineEditOutputFolder.setText(_translate("MainWindow", "Select the folder of output file meditions", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Process", None))
        self.lineeditFilePath.setText(_translate("MainWindow", "Select the folder of input audio files", None))
        self.pushButtonOutputFolder.setText(_translate("MainWindow", "Explore", None))
        self.cbxSingleFile.setText(_translate("MainWindow", "Single File", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_2), _translate("MainWindow", "Batch Process", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.dockWidgetParameterTableOscilogram.setWindowTitle(_translate("MainWindow", "Oscilogram Elements", None))
        self.tableParameterOscilogram.setToolTip(_translate("MainWindow", "Oscilogram elements  meditions", None))
        self.dockWidgetParameterTableSpectrogram.setWindowTitle(_translate("MainWindow", "Spectrogram Elements", None))
        self.tableParameterSpectrogram.setToolTip(_translate("MainWindow", "Spectrogram elements meditions", None))
        self.dock_settings.setWindowTitle(_translate("MainWindow", "Settings", None))
        self.menuExport.setTitle(_translate("MainWindow", "Export", None))
        self.menuParameters.setTitle(_translate("MainWindow", "Parameters", None))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom in", None))
        self.actionZoomIn.setShortcut(_translate("MainWindow", "+", None))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out", None))
        self.actionZoom_out.setShortcut(_translate("MainWindow", "-", None))
        self.actionSelect_all.setText(_translate("MainWindow", "Select all", None))
        self.actionSpectogram.setText(_translate("MainWindow", "Spectogram", None))
        self.actionOscilogram.setText(_translate("MainWindow", "Oscillogram", None))
        self.actionCombined.setText(_translate("MainWindow", "Combined", None))
        self.actionOscillogram_Settings.setText(_translate("MainWindow", "Oscillogram Settings", None))
        self.actionSpectogram_Settings.setText(_translate("MainWindow", "Spectrogram Settings", None))
        self.actionPlay_Sound.setText(_translate("MainWindow", "Play Sound", None))
        self.actionPlay_Sound.setShortcut(_translate("MainWindow", "Space", None))
        self.actionStop_Sound.setText(_translate("MainWindow", "Stop Sound", None))
        self.actionPause_Sound.setText(_translate("MainWindow", "Pause Sound", None))
        self.actionZoom_out_entire_file.setText(_translate("MainWindow", "Zoom out entire file", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionExcel_File.setText(_translate("MainWindow", "To Excel", None))
        self.actionView_Parameters.setText(_translate("MainWindow", "View Parameters", None))
        self.actionView_Parameters.setShortcut(_translate("MainWindow", "Ctrl+Space", None))
        self.actionParameters_Measurement.setText(_translate("MainWindow", "Parameters Measurement", None))
        self.actionDetection.setText(_translate("MainWindow", "Detection", None))
        self.actionClear_Meditions.setText(_translate("MainWindow", "Clear Meditions", None))

from Graphic_Interface.Widgets.QSignalVisualizerWidget import QSignalVisualizerWidget
import icons_rc
