# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Biologia\SISTEMA\DuettoSystem\Graphic_Interface\UI Files\SegmentationAndClasificationWindowUI.ui'
#
# Created: Wed Apr 09 09:42:27 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(769, 569)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("font: 10pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"padding:1%;"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabwidget = QtGui.QTabWidget(self.centralwidget)
        self.tabwidget.setStyleSheet(_fromUtf8(""))
        self.tabwidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabwidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabwidget.setUsesScrollButtons(True)
        self.tabwidget.setTabsClosable(False)
        self.tabwidget.setMovable(True)
        self.tabwidget.setObjectName(_fromUtf8("tabwidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QSignalVisualizerWidget(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.tabwidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButtonInputFolder = QtGui.QPushButton(self.tab_2)
        self.pushButtonInputFolder.setFlat(False)
        self.pushButtonInputFolder.setObjectName(_fromUtf8("pushButtonInputFolder"))
        self.gridLayout_4.addWidget(self.pushButtonInputFolder, 0, 1, 1, 1)
        self.listwidgetProgress = QtGui.QListWidget(self.tab_2)
        self.listwidgetProgress.setStyleSheet(_fromUtf8("background-color: rgb(217, 217, 217);"))
        self.listwidgetProgress.setObjectName(_fromUtf8("listwidgetProgress"))
        self.gridLayout_4.addWidget(self.listwidgetProgress, 4, 0, 1, 1)
        self.progressBarProcesed = QtGui.QProgressBar(self.tab_2)
        self.progressBarProcesed.setProperty("value", 0)
        self.progressBarProcesed.setObjectName(_fromUtf8("progressBarProcesed"))
        self.gridLayout_4.addWidget(self.progressBarProcesed, 6, 0, 1, 1)
        self.lineEditOutputFolder = QtGui.QLineEdit(self.tab_2)
        self.lineEditOutputFolder.setObjectName(_fromUtf8("lineEditOutputFolder"))
        self.gridLayout_4.addWidget(self.lineEditOutputFolder, 1, 0, 1, 1)
        self.lineeditFilePath = QtGui.QLineEdit(self.tab_2)
        self.lineeditFilePath.setObjectName(_fromUtf8("lineeditFilePath"))
        self.gridLayout_4.addWidget(self.lineeditFilePath, 0, 0, 1, 1)
        self.pushButtonOutputFolder = QtGui.QPushButton(self.tab_2)
        self.pushButtonOutputFolder.setObjectName(_fromUtf8("pushButtonOutputFolder"))
        self.gridLayout_4.addWidget(self.pushButtonOutputFolder, 1, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.rbttnDetection = QtGui.QRadioButton(self.groupBox)
        self.rbttnDetection.setCheckable(True)
        self.rbttnDetection.setChecked(True)
        self.rbttnDetection.setObjectName(_fromUtf8("rbttnDetection"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.rbttnDetection)
        self.rbttnSplitFile = QtGui.QRadioButton(self.groupBox)
        self.rbttnSplitFile.setObjectName(_fromUtf8("rbttnSplitFile"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.rbttnSplitFile)
        self.spboxSplitTime = QtGui.QSpinBox(self.groupBox)
        self.spboxSplitTime.setMinimum(30)
        self.spboxSplitTime.setMaximum(120)
        self.spboxSplitTime.setProperty("value", 60)
        self.spboxSplitTime.setObjectName(_fromUtf8("spboxSplitTime"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spboxSplitTime)
        self.pushButtonStart = QtGui.QPushButton(self.groupBox)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.pushButtonStart)
        self.gridLayout_4.addWidget(self.groupBox, 4, 1, 1, 2)
        self.cbxSingleFile = QtGui.QCheckBox(self.tab_2)
        self.cbxSingleFile.setObjectName(_fromUtf8("cbxSingleFile"))
        self.gridLayout_4.addWidget(self.cbxSingleFile, 0, 2, 1, 1)
        self.tabwidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabwidget)
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setStyleSheet(_fromUtf8("border-color: rgb(26, 255, 10);"))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName(_fromUtf8("horizontalScrollBar"))
        self.verticalLayout_2.addWidget(self.horizontalScrollBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 16777201))
        self.toolBar.setStyleSheet(_fromUtf8(""))
        self.toolBar.setIconSize(QtCore.QSize(20, 20))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidgetParameterTableOscilogram = QtGui.QDockWidget(MainWindow)
        self.dockWidgetParameterTableOscilogram.setObjectName(_fromUtf8("dockWidgetParameterTableOscilogram"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableParameterOscilogram = QtGui.QTableWidget(self.dockWidgetContents)
        self.tableParameterOscilogram.setObjectName(_fromUtf8("tableParameterOscilogram"))
        self.tableParameterOscilogram.setColumnCount(0)
        self.tableParameterOscilogram.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableParameterOscilogram)
        self.dockWidgetParameterTableOscilogram.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetParameterTableOscilogram)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 769, 24))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuExport = QtGui.QMenu(self.menuBar)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuParameters = QtGui.QMenu(self.menuBar)
        self.menuParameters.setObjectName(_fromUtf8("menuParameters"))
        self.menuPeak_Frecuencies = QtGui.QMenu(self.menuParameters)
        self.menuPeak_Frecuencies.setObjectName(_fromUtf8("menuPeak_Frecuencies"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionZoomIn = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoomin_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoom_out = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoomout_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon1)
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.actionSpectogram = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/spec.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpectogram.setIcon(icon2)
        self.actionSpectogram.setObjectName(_fromUtf8("actionSpectogram"))
        self.actionOscilogram = QtGui.QAction(MainWindow)
        self.actionOscilogram.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/osc.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOscilogram.setIcon(icon3)
        self.actionOscilogram.setVisible(True)
        self.actionOscilogram.setObjectName(_fromUtf8("actionOscilogram"))
        self.actionCombined = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/combined.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCombined.setIcon(icon4)
        self.actionCombined.setObjectName(_fromUtf8("actionCombined"))
        self.actionOscillogram_Settings = QtGui.QAction(MainWindow)
        self.actionOscillogram_Settings.setObjectName(_fromUtf8("actionOscillogram_Settings"))
        self.actionSpectogram_Settings = QtGui.QAction(MainWindow)
        self.actionSpectogram_Settings.setObjectName(_fromUtf8("actionSpectogram_Settings"))
        self.actionPlay_Sound = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02049_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay_Sound.setIcon(icon5)
        self.actionPlay_Sound.setObjectName(_fromUtf8("actionPlay_Sound"))
        self.actionStop_Sound = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02051_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop_Sound.setIcon(icon6)
        self.actionStop_Sound.setObjectName(_fromUtf8("actionStop_Sound"))
        self.actionPause_Sound = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/pausa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause_Sound.setIcon(icon7)
        self.actionPause_Sound.setObjectName(_fromUtf8("actionPause_Sound"))
        self.actionZoom_out_entire_file = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoom_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out_entire_file.setIcon(icon8)
        self.actionZoom_out_entire_file.setObjectName(_fromUtf8("actionZoom_out_entire_file"))
        self.actionCopy = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/copy_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon9)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/paste_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon10)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionCut = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/cut_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon11)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionMeditions = QtGui.QAction(MainWindow)
        self.actionMeditions.setObjectName(_fromUtf8("actionMeditions"))
        self.actionView_Parameters = QtGui.QAction(MainWindow)
        self.actionView_Parameters.setCheckable(True)
        self.actionView_Parameters.setObjectName(_fromUtf8("actionView_Parameters"))
        self.actionDetection = QtGui.QAction(MainWindow)
        self.actionDetection.setObjectName(_fromUtf8("actionDetection"))
        self.actionClear_Meditions = QtGui.QAction(MainWindow)
        self.actionClear_Meditions.setObjectName(_fromUtf8("actionClear_Meditions"))
        self.actionView_Threshold = QtGui.QAction(MainWindow)
        self.actionView_Threshold.setCheckable(True)
        self.actionView_Threshold.setObjectName(_fromUtf8("actionView_Threshold"))
        self.actionTemporal_Elements = QtGui.QAction(MainWindow)
        self.actionTemporal_Elements.setCheckable(True)
        self.actionTemporal_Elements.setChecked(True)
        self.actionTemporal_Elements.setObjectName(_fromUtf8("actionTemporal_Elements"))
        self.actionSpectral_Elements = QtGui.QAction(MainWindow)
        self.actionSpectral_Elements.setCheckable(True)
        self.actionSpectral_Elements.setChecked(True)
        self.actionSpectral_Elements.setObjectName(_fromUtf8("actionSpectral_Elements"))
        self.actionSpectral_Locations = QtGui.QAction(MainWindow)
        self.actionSpectral_Locations.setCheckable(True)
        self.actionSpectral_Locations.setChecked(True)
        self.actionSpectral_Locations.setObjectName(_fromUtf8("actionSpectral_Locations"))
        self.actionTemporal_Numbers = QtGui.QAction(MainWindow)
        self.actionTemporal_Numbers.setCheckable(True)
        self.actionTemporal_Numbers.setChecked(True)
        self.actionTemporal_Numbers.setObjectName(_fromUtf8("actionTemporal_Numbers"))
        self.actionSpectral_Numbers = QtGui.QAction(MainWindow)
        self.actionSpectral_Numbers.setCheckable(True)
        self.actionSpectral_Numbers.setChecked(True)
        self.actionSpectral_Numbers.setObjectName(_fromUtf8("actionSpectral_Numbers"))
        self.actionSub_Elements_Peaks = QtGui.QAction(MainWindow)
        self.actionSub_Elements_Peaks.setCheckable(True)
        self.actionSub_Elements_Peaks.setObjectName(_fromUtf8("actionSub_Elements_Peaks"))
        self.actionElements_Peaks = QtGui.QAction(MainWindow)
        self.actionElements_Peaks.setCheckable(True)
        self.actionElements_Peaks.setObjectName(_fromUtf8("actionElements_Peaks"))
        self.actionOsgram_Image = QtGui.QAction(MainWindow)
        self.actionOsgram_Image.setObjectName(_fromUtf8("actionOsgram_Image"))
        self.actionSpecgram_Image = QtGui.QAction(MainWindow)
        self.actionSpecgram_Image.setObjectName(_fromUtf8("actionSpecgram_Image"))
        self.actionTemporal_Locations = QtGui.QAction(MainWindow)
        self.actionTemporal_Locations.setCheckable(True)
        self.actionTemporal_Locations.setChecked(True)
        self.actionTemporal_Locations.setObjectName(_fromUtf8("actionTemporal_Locations"))
        self.actionCombined_Image = QtGui.QAction(MainWindow)
        self.actionCombined_Image.setObjectName(_fromUtf8("actionCombined_Image"))
        self.actionFull_Screen = QtGui.QAction(MainWindow)
        self.actionFull_Screen.setCheckable(True)
        self.actionFull_Screen.setObjectName(_fromUtf8("actionFull_Screen"))
        self.toolBar.addAction(self.actionPlay_Sound)
        self.toolBar.addAction(self.actionPause_Sound)
        self.toolBar.addAction(self.actionStop_Sound)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addAction(self.actionZoom_out_entire_file)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCombined)
        self.toolBar.addAction(self.actionOscilogram)
        self.toolBar.addAction(self.actionSpectogram)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDetection)
        self.menuExport.addAction(self.actionMeditions)
        self.menuExport.addAction(self.actionOsgram_Image)
        self.menuExport.addAction(self.actionSpecgram_Image)
        self.menuExport.addAction(self.actionCombined_Image)
        self.menuPeak_Frecuencies.addAction(self.actionElements_Peaks)
        self.menuPeak_Frecuencies.addAction(self.actionSub_Elements_Peaks)
        self.menuParameters.addAction(self.actionView_Parameters)
        self.menuParameters.addAction(self.actionView_Threshold)
        self.menuParameters.addAction(self.actionTemporal_Elements)
        self.menuParameters.addAction(self.actionTemporal_Numbers)
        self.menuParameters.addAction(self.actionTemporal_Locations)
        self.menuParameters.addAction(self.actionSpectral_Elements)
        self.menuParameters.addAction(self.actionSpectral_Numbers)
        self.menuParameters.addAction(self.actionSpectral_Locations)
        self.menuParameters.addAction(self.menuPeak_Frecuencies.menuAction())
        self.menuParameters.addAction(self.actionFull_Screen)
        self.menuBar.addAction(self.menuExport.menuAction())
        self.menuBar.addAction(self.menuParameters.menuAction())

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButtonInputFolder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.selectInputFolder)
        QtCore.QObject.connect(self.pushButtonOutputFolder, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.selectOutputFolder)
        QtCore.QObject.connect(self.pushButtonStart, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.startBatchProcess)
        QtCore.QObject.connect(self.actionView_Threshold, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), MainWindow.setVisibleThreshold)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Duetto Sound Lab", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab), _translate("MainWindow", "Detection", None))
        self.pushButtonInputFolder.setText(_translate("MainWindow", "Explore", None))
        self.lineEditOutputFolder.setText(_translate("MainWindow", "Select the folder of output procesed files", None))
        self.lineeditFilePath.setText(_translate("MainWindow", "Select the folder of input audio files", None))
        self.pushButtonOutputFolder.setText(_translate("MainWindow", "Explore", None))
        self.groupBox.setTitle(_translate("MainWindow", "Action", None))
        self.rbttnDetection.setText(_translate("MainWindow", "Detection", None))
        self.rbttnSplitFile.setText(_translate("MainWindow", "Split Files", None))
        self.spboxSplitTime.setSuffix(_translate("MainWindow", "sec", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Process", None))
        self.cbxSingleFile.setText(_translate("MainWindow", "Single Excell", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_2), _translate("MainWindow", "Batch Process", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.dockWidgetParameterTableOscilogram.setWindowTitle(_translate("MainWindow", "Elements", None))
        self.tableParameterOscilogram.setToolTip(_translate("MainWindow", "Oscilogram elements  meditions", None))
        self.menuExport.setTitle(_translate("MainWindow", "Save ", None))
        self.menuParameters.setTitle(_translate("MainWindow", "View", None))
        self.menuPeak_Frecuencies.setTitle(_translate("MainWindow", "Peak Frecuencies", None))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom in", None))
        self.actionZoomIn.setShortcut(_translate("MainWindow", "+", None))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out", None))
        self.actionZoom_out.setShortcut(_translate("MainWindow", "-", None))
        self.actionSpectogram.setText(_translate("MainWindow", "Spectogram", None))
        self.actionOscilogram.setText(_translate("MainWindow", "Oscillogram", None))
        self.actionCombined.setText(_translate("MainWindow", "Combined", None))
        self.actionOscillogram_Settings.setText(_translate("MainWindow", "Oscillogram Settings", None))
        self.actionSpectogram_Settings.setText(_translate("MainWindow", "Spectrogram Settings", None))
        self.actionPlay_Sound.setText(_translate("MainWindow", "Play Sound", None))
        self.actionPlay_Sound.setShortcut(_translate("MainWindow", "Space", None))
        self.actionStop_Sound.setText(_translate("MainWindow", "Stop Sound", None))
        self.actionPause_Sound.setText(_translate("MainWindow", "Pause Sound", None))
        self.actionZoom_out_entire_file.setText(_translate("MainWindow", "Zoom out entire file", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionMeditions.setText(_translate("MainWindow", "Meditions", None))
        self.actionView_Parameters.setText(_translate("MainWindow", "Parameters", None))
        self.actionView_Parameters.setShortcut(_translate("MainWindow", "Ctrl+Space", None))
        self.actionDetection.setText(_translate("MainWindow", "Detection", None))
        self.actionDetection.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionClear_Meditions.setText(_translate("MainWindow", "Clear Meditions", None))
        self.actionClear_Meditions.setShortcut(_translate("MainWindow", "Alt+E", None))
        self.actionView_Threshold.setText(_translate("MainWindow", "Threshold", None))
        self.actionTemporal_Elements.setText(_translate("MainWindow", "Temporal Elements", None))
        self.actionSpectral_Elements.setText(_translate("MainWindow", "Spectral Elements", None))
        self.actionSpectral_Locations.setText(_translate("MainWindow", "Spectral Locations", None))
        self.actionTemporal_Numbers.setText(_translate("MainWindow", "Temporal Numbers", None))
        self.actionSpectral_Numbers.setText(_translate("MainWindow", "Spectral Numbers", None))
        self.actionSub_Elements_Peaks.setText(_translate("MainWindow", "Sub Elements Peaks", None))
        self.actionElements_Peaks.setText(_translate("MainWindow", "Elements Peaks", None))
        self.actionOsgram_Image.setText(_translate("MainWindow", "Osgram Image", None))
        self.actionSpecgram_Image.setText(_translate("MainWindow", "Specgram Image", None))
        self.actionTemporal_Locations.setText(_translate("MainWindow", "Temporal Locations", None))
        self.actionCombined_Image.setText(_translate("MainWindow", "Combined Image", None))
        self.actionFull_Screen.setText(_translate("MainWindow", "Full Screen", None))

from Graphic_Interface.Widgets.QSignalVisualizerWidget import QSignalVisualizerWidget
import icons_rc
