from sound_lab_core.Segmentation.Adapters.AbsDecayEnvelopeDetectorAdapter import AbsDecayEnvelopeDetectorAdapter
from sound_lab_core.Segmentation.Adapters.ManualDetectorAdapter import ManualDetectorAdapter
from sound_lab_core.Segmentation.Adapters.AdaptThreshDetectorAdapter import AdaptThreshDetectorAdapter
from sound_lab_core.Segmentation.Adapters.GrabCutDetectorAdapter import GrabCutDetectorAdapter
from sound_lab_core.Segmentation.Adapters.IntervalMaxMeanDetectorAdapter import IntervalMaxMeanDetectorAdapter
from sound_lab_core.Segmentation.Adapters.IntervalPowerSpectrumDetectorAdapter import IntervalPowerSpectrumDetectorAdapter
from sound_lab_core.Segmentation.Adapters.AbsDecayEnvelopeDetectorAdapter import AbsDecayEnvelopeDetectorAdapter
from sound_lab_core.Segmentation.Adapters.WatershedDetectorAdapter import WatershedDetectorAdapter
from sound_lab_core.Segmentation.Adapters.IntervalMaxMeanDetectorAdapter import IntervalMaxMeanDetectorAdapter
from sound_lab_core.Segmentation.Adapters.ManualDetectorAdapter import ManualDetectorAdapter
from sound_lab_core.Segmentation.Adapters.AdaptThreshDetectorAdapter import AdaptThreshDetectorAdapter
from sound_lab_core.Segmentation.Adapters.GrabCutDetectorAdapter import GrabCutDetectorAdapter
from sound_lab_core.Segmentation.Adapters.IntervalPowerSpectrumDetectorAdapter import \
    IntervalPowerSpectrumDetectorAdapter
from sound_lab_core.Segmentation.Adapters.IntervalRmsDetectorAdapter import IntervalRmsDetectorAdapter