from EnvelopeTransform import Envelope
from AveragePowSpectrumTransform import AveragePowSpec
from InstantFrequenciesTransform import InstantFrequencies
from LogarithmicPowSpectrumTransform import LogarithmicPowSpec
from OneDimensionalTransform import OneDimensionalTransform
from pyqtgraph.parametertree.parameterTypes import ListParameter
from pyqtgraph.parametertree import Parameter, ParameterTree
from duetto.audio_signals import AudioSignal
from graphic_interface.windows.ParameterList import DuettoListParameterItem




