from duetto.dimensional_transformations.one_dimensional_transforms.EnvelopeTransform import Envelope
from duetto.dimensional_transformations.one_dimensional_transforms.AveragePowSpectrumTransform import AveragePowSpec
from duetto.dimensional_transformations.one_dimensional_transforms.InstantFrequenciesTransform import InstantFrequencies
from duetto.dimensional_transformations.one_dimensional_transforms.LogarithmicPowSpectrumTransform import LogarithmicPowSpec
from duetto.dimensional_transformations.one_dimensional_transforms.OneDimensionalTransform import OneDimensionalTransform
from pyqtgraph.parametertree.parameterTypes import ListParameter
from pyqtgraph.parametertree import Parameter, ParameterTree
from duetto.audio_signals import AudioSignal
from graphic_interface.windows.ParameterList import DuettoListParameterItem




