# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DuettoUserInterface.ui'
#
# Created: Mon Nov 25 16:26:13 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(837, 579)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 841, 511))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAcceptDrops(True)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.signalVisualizer = QSignalVisualizerWidget(self.tab)
        self.signalVisualizer.setGeometry(QtCore.QRect(0, 0, 711, 421))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalVisualizer.sizePolicy().hasHeightForWidth())
        self.signalVisualizer.setSizePolicy(sizePolicy)
        self.signalVisualizer.setSizeIncrement(QtCore.QSize(2, 2))
        self.signalVisualizer.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.signalVisualizer.setAcceptDrops(True)
        self.signalVisualizer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.signalVisualizer.setAutoFillBackground(True)
        self.signalVisualizer.setObjectName(_fromUtf8("signalVisualizer"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/SignalProcessing.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/flow.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon1, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBoxBatchProcess = QtGui.QGroupBox(self.tab_3)
        self.groupBoxBatchProcess.setGeometry(QtCore.QRect(0, 0, 611, 451))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxBatchProcess.sizePolicy().hasHeightForWidth())
        self.groupBoxBatchProcess.setSizePolicy(sizePolicy)
        self.groupBoxBatchProcess.setTitle(_fromUtf8(""))
        self.groupBoxBatchProcess.setObjectName(_fromUtf8("groupBoxBatchProcess"))
        self.progressBar = QtGui.QProgressBar(self.groupBoxBatchProcess)
        self.progressBar.setGeometry(QtCore.QRect(30, 420, 541, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.lineEdit = QtGui.QLineEdit(self.groupBoxBatchProcess)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 421, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(self.groupBoxBatchProcess)
        self.label.setGeometry(QtCore.QRect(30, 20, 191, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Unicode MS"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(self.groupBoxBatchProcess)
        self.pushButton.setGeometry(QtCore.QRect(460, 50, 71, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.textEdit = QtGui.QTextEdit(self.groupBoxBatchProcess)
        self.textEdit.setGeometry(QtCore.QRect(30, 100, 531, 301))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalScrollBar = QtGui.QScrollBar(self.groupBoxBatchProcess)
        self.verticalScrollBar.setGeometry(QtCore.QRect(560, 100, 16, 301))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName(_fromUtf8("verticalScrollBar"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/batch.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_3, icon2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setWindowOpacity(1.0)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuEdicion = QtGui.QMenu(self.menubar)
        self.menuEdicion.setObjectName(_fromUtf8("menuEdicion"))
        self.menuGraficar = QtGui.QMenu(self.menubar)
        self.menuGraficar.setObjectName(_fromUtf8("menuGraficar"))
        self.menuInferencia = QtGui.QMenu(self.menubar)
        self.menuInferencia.setObjectName(_fromUtf8("menuInferencia"))
        self.menuSegment = QtGui.QMenu(self.menuInferencia)
        self.menuSegment.setObjectName(_fromUtf8("menuSegment"))
        self.menuSound = QtGui.QMenu(self.menubar)
        self.menuSound.setObjectName(_fromUtf8("menuSound"))
        self.menuSound_2 = QtGui.QMenu(self.menubar)
        self.menuSound_2.setObjectName(_fromUtf8("menuSound_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/fileopen.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbrir.setIcon(icon3)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionCortar = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/cut.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCortar.setIcon(icon4)
        self.actionCortar.setObjectName(_fromUtf8("actionCortar"))
        self.actionCopiar = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/copy.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCopiar.setIcon(icon5)
        self.actionCopiar.setObjectName(_fromUtf8("actionCopiar"))
        self.actionPegar = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/paste.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPegar.setIcon(icon6)
        self.actionPegar.setObjectName(_fromUtf8("actionPegar"))
        self.actionOpciones = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/options.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpciones.setIcon(icon7)
        self.actionOpciones.setObjectName(_fromUtf8("actionOpciones"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/save")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSave.setIcon(icon8)
        self.actionSave.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/exit.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExit.setIcon(icon9)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionRefresh_Signal = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/refresh.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRefresh_Signal.setIcon(icon10)
        self.actionRefresh_Signal.setObjectName(_fromUtf8("actionRefresh_Signal"))
        self.actionZoom_IN = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/zoomIn.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_IN.setIcon(icon11)
        self.actionZoom_IN.setObjectName(_fromUtf8("actionZoom_IN"))
        self.actionZoom_Out = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/zoomOut.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_Out.setIcon(icon12)
        self.actionZoom_Out.setObjectName(_fromUtf8("actionZoom_Out"))
        self.actionReverse = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/reverse.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionReverse.setIcon(icon13)
        self.actionReverse.setObjectName(_fromUtf8("actionReverse"))
        self.actionFilter = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/filter.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionFilter.setIcon(icon14)
        self.actionFilter.setObjectName(_fromUtf8("actionFilter"))
        self.actionClear_Silence = QtGui.QAction(MainWindow)
        self.actionClear_Silence.setObjectName(_fromUtf8("actionClear_Silence"))
        self.actionNormalize = QtGui.QAction(MainWindow)
        self.actionNormalize.setObjectName(_fromUtf8("actionNormalize"))
        self.actionPlay = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/play.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPlay.setIcon(icon15)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionElements = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/stop.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionElements.setIcon(icon16)
        self.actionElements.setObjectName(_fromUtf8("actionElements"))
        self.actionRms = QtGui.QAction(MainWindow)
        self.actionRms.setObjectName(_fromUtf8("actionRms"))
        self.actionEnvelope = QtGui.QAction(MainWindow)
        self.actionEnvelope.setObjectName(_fromUtf8("actionEnvelope"))
        self.actionMean = QtGui.QAction(MainWindow)
        self.actionMean.setObjectName(_fromUtf8("actionMean"))
        self.actionUniform = QtGui.QAction(MainWindow)
        self.actionUniform.setObjectName(_fromUtf8("actionUniform"))
        self.actionPseudoUniform = QtGui.QAction(MainWindow)
        self.actionPseudoUniform.setObjectName(_fromUtf8("actionPseudoUniform"))
        self.actionNoiseDetection = QtGui.QAction(MainWindow)
        self.actionNoiseDetection.setObjectName(_fromUtf8("actionNoiseDetection"))
        self.actionPeaks = QtGui.QAction(MainWindow)
        self.actionPeaks.setObjectName(_fromUtf8("actionPeaks"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionInsert_Silence = QtGui.QAction(MainWindow)
        self.actionInsert_Silence.setObjectName(_fromUtf8("actionInsert_Silence"))
        self.actionZoom_None = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/zoomNone.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_None.setIcon(icon17)
        self.actionZoom_None.setObjectName(_fromUtf8("actionZoom_None"))
        self.actionPause = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/pause.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPause.setIcon(icon18)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/stop.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStop.setIcon(icon19)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionScale = QtGui.QAction(MainWindow)
        self.actionScale.setObjectName(_fromUtf8("actionScale"))
        self.actionDeselect = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/UI Files/resources/deselect.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDeselect.setIcon(icon20)
        self.actionDeselect.setObjectName(_fromUtf8("actionDeselect"))
        self.actionChangePlayStatus = QtGui.QAction(MainWindow)
        self.actionChangePlayStatus.setObjectName(_fromUtf8("actionChangePlayStatus"))
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSave)
        self.menuArchivo.addAction(self.actionSave_As)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionClose)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionExit)
        self.menuArchivo.addSeparator()
        self.menuEdicion.addAction(self.actionCortar)
        self.menuEdicion.addAction(self.actionCopiar)
        self.menuEdicion.addAction(self.actionPegar)
        self.menuEdicion.addSeparator()
        self.menuEdicion.addAction(self.actionReverse)
        self.menuEdicion.addAction(self.actionFilter)
        self.menuEdicion.addAction(self.actionInsert_Silence)
        self.menuEdicion.addAction(self.actionClear_Silence)
        self.menuEdicion.addSeparator()
        self.menuEdicion.addAction(self.actionNormalize)
        self.menuEdicion.addAction(self.actionEnvelope)
        self.menuEdicion.addAction(self.actionScale)
        self.menuGraficar.addAction(self.actionOpciones)
        self.menuGraficar.addAction(self.actionRefresh_Signal)
        self.menuGraficar.addSeparator()
        self.menuGraficar.addAction(self.actionZoom_IN)
        self.menuGraficar.addAction(self.actionZoom_Out)
        self.menuGraficar.addAction(self.actionZoom_None)
        self.menuGraficar.addSeparator()
        self.menuSegment.addAction(self.actionUniform)
        self.menuSegment.addAction(self.actionPseudoUniform)
        self.menuSegment.addAction(self.actionNoiseDetection)
        self.menuInferencia.addAction(self.actionElements)
        self.menuInferencia.addAction(self.menuSegment.menuAction())
        self.menuInferencia.addAction(self.actionPeaks)
        self.menuInferencia.addAction(self.actionRms)
        self.menuInferencia.addAction(self.actionMean)
        self.menuSound_2.addAction(self.actionPlay)
        self.menuSound_2.addAction(self.actionPause)
        self.menuSound_2.addAction(self.actionStop)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEdicion.menuAction())
        self.menubar.addAction(self.menuGraficar.menuAction())
        self.menubar.addAction(self.menuInferencia.menuAction())
        self.menubar.addAction(self.menuSound.menuAction())
        self.menubar.addAction(self.menuSound_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionAbrir, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.openEvent)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.saveEvent)
        QtCore.QObject.connect(self.actionCortar, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.cut)
        QtCore.QObject.connect(self.actionCopiar, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.copy)
        QtCore.QObject.connect(self.actionPegar, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.paste)
        QtCore.QObject.connect(self.actionOpciones, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.options)
        QtCore.QObject.connect(self.actionRefresh_Signal, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.refreshSignal)
        QtCore.QObject.connect(self.actionZoom_IN, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.zoomIn)
        QtCore.QObject.connect(self.actionZoom_Out, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.zoomOut)
        QtCore.QObject.connect(self.actionReverse, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.reverse)
        QtCore.QObject.connect(self.actionClear_Silence, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.silence)
        QtCore.QObject.connect(self.actionNormalize, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.normalize)
        QtCore.QObject.connect(self.actionFilter, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.filter)
        QtCore.QObject.connect(self.actionPlay, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.play)
        QtCore.QObject.connect(self.actionElements, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.elements)
        QtCore.QObject.connect(self.actionRms, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.rms)
        QtCore.QObject.connect(self.actionEnvelope, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.envelope)
        QtCore.QObject.connect(self.actionPeaks, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.peaks)
        QtCore.QObject.connect(self.actionMean, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.mean)
        QtCore.QObject.connect(self.actionUniform, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.uniformSegmenter)
        QtCore.QObject.connect(self.actionPseudoUniform, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.pseudoUniformSegmenter)
        QtCore.QObject.connect(self.actionInsert_Silence, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.insertSilence)
        QtCore.QObject.connect(self.actionZoom_None, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.zoomNone)
        QtCore.QObject.connect(self.actionPause, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.pause)
        QtCore.QObject.connect(self.actionStop, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.stop)
        QtCore.QObject.connect(self.actionScale, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.scale)
        QtCore.QObject.connect(self.actionChangePlayStatus, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.switchPlayStatus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Duetto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Signal Processing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Flow Jobs", None))
        self.label.setText(_translate("MainWindow", "Select the Path of the files", None))
        self.pushButton.setText(_translate("MainWindow", "Process", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Batch Processing", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "File", None))
        self.menuEdicion.setTitle(_translate("MainWindow", "Edit", None))
        self.menuGraficar.setTitle(_translate("MainWindow", "Graphics", None))
        self.menuInferencia.setTitle(_translate("MainWindow", "Detection", None))
        self.menuSegment.setTitle(_translate("MainWindow", "Segment", None))
        self.menuSound.setTitle(_translate("MainWindow", "Clasification", None))
        self.menuSound_2.setTitle(_translate("MainWindow", "Sound", None))
        self.actionAbrir.setText(_translate("MainWindow", "Open", None))
        self.actionAbrir.setToolTip(_translate("MainWindow", "Open an audio file", None))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionCortar.setText(_translate("MainWindow", "Cut", None))
        self.actionCortar.setToolTip(_translate("MainWindow", "Cut the selected piece", None))
        self.actionCortar.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionCopiar.setText(_translate("MainWindow", "Copy", None))
        self.actionCopiar.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.actionPegar.setText(_translate("MainWindow", "Paste", None))
        self.actionPegar.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.actionOpciones.setText(_translate("MainWindow", "Options", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Saves the work", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+G", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit the program", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc", None))
        self.actionRefresh_Signal.setText(_translate("MainWindow", "Refresh Signal", None))
        self.actionRefresh_Signal.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionZoom_IN.setText(_translate("MainWindow", "Zoom In", None))
        self.actionZoom_IN.setShortcut(_translate("MainWindow", "+", None))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out", None))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "-", None))
        self.actionReverse.setText(_translate("MainWindow", "Reverse", None))
        self.actionFilter.setText(_translate("MainWindow", "Filter", None))
        self.actionClear_Silence.setText(_translate("MainWindow", "Clear/Silence", None))
        self.actionNormalize.setText(_translate("MainWindow", "Normalize", None))
        self.actionPlay.setText(_translate("MainWindow", "Play", None))
        self.actionElements.setText(_translate("MainWindow", "Elements", None))
        self.actionRms.setText(_translate("MainWindow", "RMS", None))
        self.actionEnvelope.setText(_translate("MainWindow", "Envelope", None))
        self.actionMean.setText(_translate("MainWindow", "Mean", None))
        self.actionUniform.setText(_translate("MainWindow", "Uniform", None))
        self.actionPseudoUniform.setText(_translate("MainWindow", "PseudoUniform", None))
        self.actionNoiseDetection.setText(_translate("MainWindow", "Parametized", None))
        self.actionPeaks.setText(_translate("MainWindow", "Peaks", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionInsert_Silence.setText(_translate("MainWindow", "Insert Silence", None))
        self.actionZoom_None.setText(_translate("MainWindow", "Zoom None", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionScale.setText(_translate("MainWindow", "Scale", None))
        self.actionDeselect.setText(_translate("MainWindow", "Deselect", None))
        self.actionDeselect.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionChangePlayStatus.setText(_translate("MainWindow", "ChangePlayStatus", None))
        self.actionChangePlayStatus.setShortcut(_translate("MainWindow", "Space", None))

from QSignalVisualizerWidget import QSignalVisualizerWidget
import resources_rc
