# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Biologia\DUETTO PROGRAMS\Desktop\Sound Lab\duetto-SoundLab\graphic_interface\UI_Files\BrowseFilesWindow.ui'
#
# Created: Sat Apr 18 18:23:48 2015
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BrowseFilesWindow(object):
    def setupUi(self, BrowseFilesWindow):
        BrowseFilesWindow.setObjectName(_fromUtf8("BrowseFilesWindow"))
        BrowseFilesWindow.resize(522, 339)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BrowseFilesWindow.sizePolicy().hasHeightForWidth())
        BrowseFilesWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/duetto_logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BrowseFilesWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(BrowseFilesWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.playFile_bttn = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02049_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playFile_bttn.setIcon(icon1)
        self.playFile_bttn.setCheckable(False)
        self.playFile_bttn.setObjectName(_fromUtf8("playFile_bttn"))
        self.gridLayout.addWidget(self.playFile_bttn, 4, 9, 1, 1)
        self.folderPath_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.folderPath_lineEdit.setObjectName(_fromUtf8("folderPath_lineEdit"))
        self.gridLayout.addWidget(self.folderPath_lineEdit, 0, 0, 1, 9)
        self.folderPath_bttn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderPath_bttn.sizePolicy().hasHeightForWidth())
        self.folderPath_bttn.setSizePolicy(sizePolicy)
        self.folderPath_bttn.setMinimumSize(QtCore.QSize(30, 0))
        self.folderPath_bttn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.folderPath_bttn.setObjectName(_fromUtf8("folderPath_bttn"))
        self.gridLayout.addWidget(self.folderPath_bttn, 0, 9, 1, 1)
        self.files_tablewidget = QtGui.QTableWidget(self.centralwidget)
        self.files_tablewidget.setObjectName(_fromUtf8("files_tablewidget"))
        self.files_tablewidget.setColumnCount(4)
        self.files_tablewidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.files_tablewidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.files_tablewidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.files_tablewidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.files_tablewidget.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.files_tablewidget, 1, 0, 2, 10)
        self.fileDown_bttn = QtGui.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/downfile.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileDown_bttn.setIcon(icon2)
        self.fileDown_bttn.setObjectName(_fromUtf8("fileDown_bttn"))
        self.gridLayout.addWidget(self.fileDown_bttn, 4, 8, 1, 1)
        self.fileUp_bttn = QtGui.QPushButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/upfile.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileUp_bttn.setIcon(icon3)
        self.fileUp_bttn.setObjectName(_fromUtf8("fileUp_bttn"))
        self.gridLayout.addWidget(self.fileUp_bttn, 4, 7, 1, 1)
        self.openFile_bttn = QtGui.QPushButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/81.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFile_bttn.setIcon(icon4)
        self.openFile_bttn.setObjectName(_fromUtf8("openFile_bttn"))
        self.gridLayout.addWidget(self.openFile_bttn, 4, 6, 1, 1)
        self.invertSelection_bttn = QtGui.QPushButton(self.centralwidget)
        self.invertSelection_bttn.setObjectName(_fromUtf8("invertSelection_bttn"))
        self.gridLayout.addWidget(self.invertSelection_bttn, 4, 5, 1, 1)
        self.selectAll_bttn = QtGui.QPushButton(self.centralwidget)
        self.selectAll_bttn.setCheckable(False)
        self.selectAll_bttn.setChecked(False)
        self.selectAll_bttn.setObjectName(_fromUtf8("selectAll_bttn"))
        self.gridLayout.addWidget(self.selectAll_bttn, 4, 4, 1, 1)
        BrowseFilesWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(BrowseFilesWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BrowseFilesWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(BrowseFilesWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionFileUp = QtGui.QAction(BrowseFilesWindow)
        self.actionFileUp.setObjectName(_fromUtf8("actionFileUp"))
        self.actionFileDown = QtGui.QAction(BrowseFilesWindow)
        self.actionFileDown.setObjectName(_fromUtf8("actionFileDown"))
        self.actionPlay = QtGui.QAction(BrowseFilesWindow)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionAddFileButton = QtGui.QAction(BrowseFilesWindow)
        self.actionAddFileButton.setObjectName(_fromUtf8("actionAddFileButton"))
        self.actionSelectAll = QtGui.QAction(BrowseFilesWindow)
        self.actionSelectAll.setObjectName(_fromUtf8("actionSelectAll"))
        self.actionInvertSelection = QtGui.QAction(BrowseFilesWindow)
        self.actionInvertSelection.setObjectName(_fromUtf8("actionInvertSelection"))

        self.retranslateUi(BrowseFilesWindow)
        QtCore.QObject.connect(self.playFile_bttn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionPlay.trigger)
        QtCore.QObject.connect(self.fileDown_bttn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionFileDown.trigger)
        QtCore.QObject.connect(self.fileUp_bttn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionFileUp.trigger)
        QtCore.QObject.connect(self.openFile_bttn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionOpen.trigger)
        QtCore.QObject.connect(self.folderPath_bttn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionAddFileButton.trigger)
        QtCore.QObject.connect(self.selectAll_bttn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionSelectAll.trigger)
        QtCore.QObject.connect(self.invertSelection_bttn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.actionInvertSelection.trigger)
        QtCore.QMetaObject.connectSlotsByName(BrowseFilesWindow)

    def retranslateUi(self, BrowseFilesWindow):
        BrowseFilesWindow.setWindowTitle(QtGui.QApplication.translate("BrowseFilesWindow", "Browse Files", None, QtGui.QApplication.UnicodeUTF8))
        BrowseFilesWindow.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "The browse window allow to visualize several signals and its properties. You can select one or many to open in sound Lab.", None, QtGui.QApplication.UnicodeUTF8))
        self.playFile_bttn.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Play the first of the selected signals.", None, QtGui.QApplication.UnicodeUTF8))
        self.playFile_bttn.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.folderPath_lineEdit.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Input folder of signals to browse.", None, QtGui.QApplication.UnicodeUTF8))
        self.folderPath_lineEdit.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Seleccione la carpeta", None, QtGui.QApplication.UnicodeUTF8))
        self.folderPath_bttn.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Explore folders to add signals to the currently visualized on table.", None, QtGui.QApplication.UnicodeUTF8))
        self.folderPath_bttn.setText(QtGui.QApplication.translate("BrowseFilesWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.files_tablewidget.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Table with parameters of signals to analize them.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.files_tablewidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        item = self.files_tablewidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        item = self.files_tablewidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Creation Date", None, QtGui.QApplication.UnicodeUTF8))
        item = self.files_tablewidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDown_bttn.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Select next signal. (Next to currently selected)", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDown_bttn.setText(QtGui.QApplication.translate("BrowseFilesWindow", "File Down", None, QtGui.QApplication.UnicodeUTF8))
        self.fileUp_bttn.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Select previous signal. (Previous to currently selected)", None, QtGui.QApplication.UnicodeUTF8))
        self.fileUp_bttn.setText(QtGui.QApplication.translate("BrowseFilesWindow", "File Up", None, QtGui.QApplication.UnicodeUTF8))
        self.openFile_bttn.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Open selected signals of the table on sound Lab", None, QtGui.QApplication.UnicodeUTF8))
        self.openFile_bttn.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.invertSelection_bttn.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Invert selection of signals on table.", None, QtGui.QApplication.UnicodeUTF8))
        self.invertSelection_bttn.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAll_bttn.setToolTip(QtGui.QApplication.translate("BrowseFilesWindow", "Select all signals on table", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAll_bttn.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileUp.setText(QtGui.QApplication.translate("BrowseFilesWindow", "FileUp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileDown.setText(QtGui.QApplication.translate("BrowseFilesWindow", "FileDown", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("BrowseFilesWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddFileButton.setText(QtGui.QApplication.translate("BrowseFilesWindow", "AddFileBttn", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setText(QtGui.QApplication.translate("BrowseFilesWindow", "SelectAll", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInvertSelection.setText(QtGui.QApplication.translate("BrowseFilesWindow", "InvertSelection", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
