# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Biologia\DUETTO PROGRAMS\Desktop\Sound Lab\duetto-SoundLab\graphic_interface\UI_Files\ParametersWindow.ui'
#
# Created: Sun Aug 23 09:42:25 2015
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(817, 715)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.advanced_mode_gbox = QtGui.QGroupBox(Dialog)
        self.advanced_mode_gbox.setTitle(_fromUtf8(""))
        self.advanced_mode_gbox.setObjectName(_fromUtf8("advanced_mode_gbox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.advanced_mode_gbox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QSignalDetectorWidget(self.advanced_mode_gbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 250))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout.addWidget(self.widget)
        self.groupBox = QtGui.QGroupBox(self.advanced_mode_gbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.new_template_name_linedit = QtGui.QLineEdit(self.groupBox)
        self.new_template_name_linedit.setObjectName(_fromUtf8("new_template_name_linedit"))
        self.gridLayout_5.addWidget(self.new_template_name_linedit, 4, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.visible_spectrogram_cbox = QtGui.QCheckBox(self.groupBox_2)
        self.visible_spectrogram_cbox.setChecked(False)
        self.visible_spectrogram_cbox.setObjectName(_fromUtf8("visible_spectrogram_cbox"))
        self.verticalLayout.addWidget(self.visible_spectrogram_cbox)
        self.visible_oscilogram_cbox = QtGui.QCheckBox(self.groupBox_2)
        self.visible_oscilogram_cbox.setObjectName(_fromUtf8("visible_oscilogram_cbox"))
        self.verticalLayout.addWidget(self.visible_oscilogram_cbox)
        self.gridLayout_5.addWidget(self.groupBox_2, 6, 0, 1, 2)
        self.measurement_template_cbox = QtGui.QComboBox(self.groupBox)
        self.measurement_template_cbox.setObjectName(_fromUtf8("measurement_template_cbox"))
        self.measurement_template_cbox.addItem(_fromUtf8(""))
        self.measurement_template_cbox.addItem(_fromUtf8(""))
        self.measurement_template_cbox.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.measurement_template_cbox, 0, 0, 1, 1)
        self.remove_measurement_template_bttn = QtGui.QPushButton(self.groupBox)
        self.remove_measurement_template_bttn.setObjectName(_fromUtf8("remove_measurement_template_bttn"))
        self.gridLayout_5.addWidget(self.remove_measurement_template_bttn, 0, 1, 1, 1)
        self.save_measurement_template_as_bttn = QtGui.QPushButton(self.groupBox)
        self.save_measurement_template_as_bttn.setObjectName(_fromUtf8("save_measurement_template_as_bttn"))
        self.gridLayout_5.addWidget(self.save_measurement_template_as_bttn, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem, 5, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.advanced_mode_gbox, 8, 1, 1, 6)
        self.settings_widget = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_widget.sizePolicy().hasHeightForWidth())
        self.settings_widget.setSizePolicy(sizePolicy)
        self.settings_widget.setMinimumSize(QtCore.QSize(250, 0))
        self.settings_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.settings_widget.setStyleSheet(_fromUtf8(""))
        self.settings_widget.setObjectName(_fromUtf8("settings_widget"))
        self.gridLayout.addWidget(self.settings_widget, 0, 5, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 9, 5, 1, 1)
        self.advanced_mode_visibility_cbox = QtGui.QCheckBox(Dialog)
        self.advanced_mode_visibility_cbox.setChecked(False)
        self.advanced_mode_visibility_cbox.setObjectName(_fromUtf8("advanced_mode_visibility_cbox"))
        self.gridLayout.addWidget(self.advanced_mode_visibility_cbox, 1, 1, 1, 5)
        self.tab_parameters = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_parameters.sizePolicy().hasHeightForWidth())
        self.tab_parameters.setSizePolicy(sizePolicy)
        self.tab_parameters.setMinimumSize(QtCore.QSize(500, 0))
        self.tab_parameters.setObjectName(_fromUtf8("tab_parameters"))
        self.tab_spectral_params = QtGui.QWidget()
        self.tab_spectral_params.setObjectName(_fromUtf8("tab_spectral_params"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_spectral_params)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_spectral_params)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.time_parameter_table = QtGui.QTableWidget(self.groupBox_3)
        self.time_parameter_table.setObjectName(_fromUtf8("time_parameter_table"))
        self.time_parameter_table.setColumnCount(0)
        self.time_parameter_table.setRowCount(0)
        self.gridLayout_6.addWidget(self.time_parameter_table, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.spectral_paameters_gbox = QtGui.QGroupBox(self.tab_spectral_params)
        self.spectral_paameters_gbox.setObjectName(_fromUtf8("spectral_paameters_gbox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.spectral_paameters_gbox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.parameter_locations_table = QtGui.QTableWidget(self.spectral_paameters_gbox)
        self.parameter_locations_table.setObjectName(_fromUtf8("parameter_locations_table"))
        self.parameter_locations_table.setColumnCount(0)
        self.parameter_locations_table.setRowCount(0)
        self.gridLayout_3.addWidget(self.parameter_locations_table, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.spectral_paameters_gbox, 2, 0, 1, 1)
        self.wave_paameters_gbox = QtGui.QGroupBox(self.tab_spectral_params)
        self.wave_paameters_gbox.setObjectName(_fromUtf8("wave_paameters_gbox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wave_paameters_gbox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.wave_parameter_table = QtGui.QTableWidget(self.wave_paameters_gbox)
        self.wave_parameter_table.setObjectName(_fromUtf8("wave_parameter_table"))
        self.wave_parameter_table.setColumnCount(0)
        self.wave_parameter_table.setRowCount(0)
        self.gridLayout_4.addWidget(self.wave_parameter_table, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.wave_paameters_gbox, 1, 0, 1, 1)
        self.tab_parameters.addTab(self.tab_spectral_params, _fromUtf8(""))
        self.gridLayout.addWidget(self.tab_parameters, 0, 1, 1, 2)

        self.retranslateUi(Dialog)
        self.tab_parameters.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Parameters Window", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Measurement template", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Previsualization Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.visible_spectrogram_cbox.setText(QtGui.QApplication.translate("Dialog", "Visible Spectrogram", None, QtGui.QApplication.UnicodeUTF8))
        self.visible_oscilogram_cbox.setText(QtGui.QApplication.translate("Dialog", "Visible Oscilogram", None, QtGui.QApplication.UnicodeUTF8))
        self.measurement_template_cbox.setItemText(0, QtGui.QApplication.translate("Dialog", "Bats", None, QtGui.QApplication.UnicodeUTF8))
        self.measurement_template_cbox.setItemText(1, QtGui.QApplication.translate("Dialog", "user defined", None, QtGui.QApplication.UnicodeUTF8))
        self.measurement_template_cbox.setItemText(2, QtGui.QApplication.translate("Dialog", "other template", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_measurement_template_bttn.setText(QtGui.QApplication.translate("Dialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.save_measurement_template_as_bttn.setText(QtGui.QApplication.translate("Dialog", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_mode_visibility_cbox.setText(QtGui.QApplication.translate("Dialog", "Show Advanced Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Time Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.spectral_paameters_gbox.setTitle(QtGui.QApplication.translate("Dialog", "Spectral Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.wave_paameters_gbox.setTitle(QtGui.QApplication.translate("Dialog", "Wave Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_parameters.setTabText(self.tab_parameters.indexOf(self.tab_spectral_params), QtGui.QApplication.translate("Dialog", "Parameter Measurements", None, QtGui.QApplication.UnicodeUTF8))

from graphic_interface.widgets.QSignalDetectorWidget import QSignalDetectorWidget
