# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Fac Biologia\DUETTO PROGRAMS\Desktop\Sound Lab\duetto-SoundLab\graphic_interface\UI_Files\SoundLabWindow.ui'
#
# Created: Thu Feb 05 11:03:05 2015
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DuettoMainWindow(object):
    def setupUi(self, DuettoMainWindow):
        DuettoMainWindow.setObjectName(_fromUtf8("DuettoMainWindow"))
        DuettoMainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        DuettoMainWindow.resize(752, 521)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DuettoMainWindow.sizePolicy().hasHeightForWidth())
        DuettoMainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/duetto_logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DuettoMainWindow.setWindowIcon(icon)
        DuettoMainWindow.setAutoFillBackground(False)
        DuettoMainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(DuettoMainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        DuettoMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DuettoMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 21))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet(_fromUtf8(""))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setGeometry(QtCore.QRect(119, 154, 148, 121))
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setStyleSheet(_fromUtf8(""))
        self.menuFile.setTearOffEnabled(False)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave_Images = QtGui.QMenu(self.menuFile)
        self.menuSave_Images.setObjectName(_fromUtf8("menuSave_Images"))
        self.menuRecentSignals = QtGui.QMenu(self.menuFile)
        self.menuRecentSignals.setObjectName(_fromUtf8("menuRecentSignals"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setStyleSheet(_fromUtf8(""))
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setStyleSheet(_fromUtf8(""))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuGenerate = QtGui.QMenu(self.menuEdit)
        self.menuGenerate.setObjectName(_fromUtf8("menuGenerate"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setStyleSheet(_fromUtf8(""))
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuSound = QtGui.QMenu(self.menubar)
        self.menuSound.setStyleSheet(_fromUtf8(""))
        self.menuSound.setObjectName(_fromUtf8("menuSound"))
        self.menuPlay_Speed = QtGui.QMenu(self.menuSound)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/Macromedia.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuPlay_Speed.setIcon(icon1)
        self.menuPlay_Speed.setObjectName(_fromUtf8("menuPlay_Speed"))
        DuettoMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DuettoMainWindow)
        self.statusbar.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DuettoMainWindow.setStatusBar(self.statusbar)
        self.toolBar = SoundLabToolBarWidget(DuettoMainWindow)
        self.toolBar.setStyleSheet(_fromUtf8(""))
        self.toolBar.setIconSize(QtCore.QSize(20, 20))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        DuettoMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionZoomIn = QtGui.QAction(DuettoMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoomin_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon2)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoom_out = QtGui.QAction(DuettoMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoomout_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon3)
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.actionSpectogram = QtGui.QAction(DuettoMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/spec.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpectogram.setIcon(icon4)
        self.actionSpectogram.setObjectName(_fromUtf8("actionSpectogram"))
        self.actionOscilogram = QtGui.QAction(DuettoMainWindow)
        self.actionOscilogram.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/osc.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOscilogram.setIcon(icon5)
        self.actionOscilogram.setVisible(True)
        self.actionOscilogram.setObjectName(_fromUtf8("actionOscilogram"))
        self.actionCombined = QtGui.QAction(DuettoMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/combined.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCombined.setIcon(icon6)
        self.actionCombined.setObjectName(_fromUtf8("actionCombined"))
        self.actionPlay_Sound = QtGui.QAction(DuettoMainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02049_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay_Sound.setIcon(icon7)
        self.actionPlay_Sound.setObjectName(_fromUtf8("actionPlay_Sound"))
        self.actionStop_Sound = QtGui.QAction(DuettoMainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/02051_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop_Sound.setIcon(icon8)
        self.actionStop_Sound.setObjectName(_fromUtf8("actionStop_Sound"))
        self.actionPause_Sound = QtGui.QAction(DuettoMainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/pausa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause_Sound.setIcon(icon9)
        self.actionPause_Sound.setObjectName(_fromUtf8("actionPause_Sound"))
        self.actionZoom_out_entire_file = QtGui.QAction(DuettoMainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/zoom_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out_entire_file.setIcon(icon10)
        self.actionZoom_out_entire_file.setObjectName(_fromUtf8("actionZoom_out_entire_file"))
        self.actionCopy = QtGui.QAction(DuettoMainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/copy_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon11)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(DuettoMainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/paste_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon12)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionCut = QtGui.QAction(DuettoMainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/cut_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon13)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionRecord = QtGui.QAction(DuettoMainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/record_26x26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon14)
        self.actionRecord.setObjectName(_fromUtf8("actionRecord"))
        self.actionUndo = QtGui.QAction(DuettoMainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon15)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(DuettoMainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon16)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionZoom_Cursor = QtGui.QAction(DuettoMainWindow)
        self.actionZoom_Cursor.setCheckable(True)
        self.actionZoom_Cursor.setChecked(True)
        self.actionZoom_Cursor.setAutoRepeat(False)
        self.actionZoom_Cursor.setPriority(QtGui.QAction.HighPriority)
        self.actionZoom_Cursor.setObjectName(_fromUtf8("actionZoom_Cursor"))
        self.actionPointer_Cursor = QtGui.QAction(DuettoMainWindow)
        self.actionPointer_Cursor.setCheckable(True)
        self.actionPointer_Cursor.setAutoRepeat(False)
        self.actionPointer_Cursor.setPriority(QtGui.QAction.HighPriority)
        self.actionPointer_Cursor.setObjectName(_fromUtf8("actionPointer_Cursor"))
        self.actionFull_Screen = QtGui.QAction(DuettoMainWindow)
        self.actionFull_Screen.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/Position.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFull_Screen.setIcon(icon17)
        self.actionFull_Screen.setObjectName(_fromUtf8("actionFull_Screen"))
        self.actionOsc_Image = QtGui.QAction(DuettoMainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/Camera.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOsc_Image.setIcon(icon18)
        self.actionOsc_Image.setObjectName(_fromUtf8("actionOsc_Image"))
        self.actionSpecgram_Image = QtGui.QAction(DuettoMainWindow)
        self.actionSpecgram_Image.setIcon(icon18)
        self.actionSpecgram_Image.setObjectName(_fromUtf8("actionSpecgram_Image"))
        self.actionCombined_Image = QtGui.QAction(DuettoMainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/Photofiltre.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCombined_Image.setIcon(icon19)
        self.actionCombined_Image.setObjectName(_fromUtf8("actionCombined_Image"))
        self.actionRectangular_Cursor = QtGui.QAction(DuettoMainWindow)
        self.actionRectangular_Cursor.setCheckable(True)
        self.actionRectangular_Cursor.setObjectName(_fromUtf8("actionRectangular_Cursor"))
        self.actionRectangular_Eraser = QtGui.QAction(DuettoMainWindow)
        self.actionRectangular_Eraser.setCheckable(True)
        self.actionRectangular_Eraser.setObjectName(_fromUtf8("actionRectangular_Eraser"))
        self.actionSwitchPlayStatus = QtGui.QAction(DuettoMainWindow)
        self.actionSwitchPlayStatus.setObjectName(_fromUtf8("actionSwitchPlayStatus"))
        self.actionPlayLoop = QtGui.QAction(DuettoMainWindow)
        self.actionPlayLoop.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/myappicons/Behavior.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayLoop.setIcon(icon20)
        self.actionPlayLoop.setObjectName(_fromUtf8("actionPlayLoop"))
        self.menuSave_Images.addAction(self.actionOsc_Image)
        self.menuSave_Images.addAction(self.actionSpecgram_Image)
        self.menuSave_Images.addAction(self.actionCombined_Image)
        self.menuRecentSignals.addSeparator()
        self.menuFile.addAction(self.menuRecentSignals.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSave_Images.menuAction())
        self.menuFile.addSeparator()
        self.menuTools.addAction(self.actionZoomIn)
        self.menuTools.addAction(self.actionZoom_out)
        self.menuTools.addAction(self.actionZoom_out_entire_file)
        self.menuTools.addAction(self.actionFull_Screen)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionZoom_Cursor)
        self.menuTools.addAction(self.actionPointer_Cursor)
        self.menuTools.addAction(self.actionRectangular_Cursor)
        self.menuTools.addAction(self.actionRectangular_Eraser)
        self.menuTools.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addSeparator()
        self.menuEdit.addSeparator()
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuGenerate.menuAction())
        self.menuView.addAction(self.actionOscilogram)
        self.menuView.addAction(self.actionSpectogram)
        self.menuView.addAction(self.actionCombined)
        self.menuView.addSeparator()
        self.menuSound.addSeparator()
        self.menuSound.addAction(self.menuPlay_Speed.menuAction())
        self.menuSound.addSeparator()
        self.menuSound.addAction(self.actionPlay_Sound)
        self.menuSound.addAction(self.actionStop_Sound)
        self.menuSound.addAction(self.actionPause_Sound)
        self.menuSound.addAction(self.actionRecord)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSound.menuAction())

        self.retranslateUi(DuettoMainWindow)
        QtCore.QObject.connect(self.actionSwitchPlayStatus, QtCore.SIGNAL(_fromUtf8("triggered()")), DuettoMainWindow.switchPlayStatus)
        QtCore.QMetaObject.connectSlotsByName(DuettoMainWindow)

    def retranslateUi(self, DuettoMainWindow):
        DuettoMainWindow.setWindowTitle(QtGui.QApplication.translate("DuettoMainWindow", "Duetto Sound Lab", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave_Images.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Save Images", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecentSignals.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Recent Signals", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGenerate.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSound.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlay_Speed.setTitle(QtGui.QApplication.translate("DuettoMainWindow", "Play Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("DuettoMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("DuettoMainWindow", "Zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setText(QtGui.QApplication.translate("DuettoMainWindow", "Zoom out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpectogram.setText(QtGui.QApplication.translate("DuettoMainWindow", "Spectogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOscilogram.setText(QtGui.QApplication.translate("DuettoMainWindow", "Oscillogram", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCombined.setText(QtGui.QApplication.translate("DuettoMainWindow", "Combined", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Sound.setText(QtGui.QApplication.translate("DuettoMainWindow", "Play Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Sound.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Sound.setText(QtGui.QApplication.translate("DuettoMainWindow", "Stop Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause_Sound.setText(QtGui.QApplication.translate("DuettoMainWindow", "Pause Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause_Sound.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_out_entire_file.setText(QtGui.QApplication.translate("DuettoMainWindow", "Zoom out entire file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("DuettoMainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("DuettoMainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("DuettoMainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecord.setText(QtGui.QApplication.translate("DuettoMainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("DuettoMainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("DuettoMainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Cursor.setText(QtGui.QApplication.translate("DuettoMainWindow", "Zoom Cursor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom_Cursor.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPointer_Cursor.setText(QtGui.QApplication.translate("DuettoMainWindow", "Pointer Cursor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPointer_Cursor.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+Shift+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Screen.setText(QtGui.QApplication.translate("DuettoMainWindow", "Full Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Screen.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Ctrl+S, Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOsc_Image.setText(QtGui.QApplication.translate("DuettoMainWindow", "Oscilogram Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpecgram_Image.setText(QtGui.QApplication.translate("DuettoMainWindow", "Spectrogram Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCombined_Image.setText(QtGui.QApplication.translate("DuettoMainWindow", "Combined Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRectangular_Cursor.setText(QtGui.QApplication.translate("DuettoMainWindow", "Rectangular Cursor", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRectangular_Eraser.setText(QtGui.QApplication.translate("DuettoMainWindow", "Rectangular Eraser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitchPlayStatus.setText(QtGui.QApplication.translate("DuettoMainWindow", "switchPlayStatus", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitchPlayStatus.setShortcut(QtGui.QApplication.translate("DuettoMainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayLoop.setText(QtGui.QApplication.translate("DuettoMainWindow", "PlayLoop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayLoop.setToolTip(QtGui.QApplication.translate("DuettoMainWindow", "Play Loop", None, QtGui.QApplication.UnicodeUTF8))

from graphic_interface.widgets.SoundLabToolBar import SoundLabToolBarWidget
import icons_rc
