from StartLocationAdapter import StartLocationAdapter
from CenterLocationAdapter import CenterLocationAdapter
from EndLocationAdapter import EndLocationAdapter
from MeanLocationAdapter import MeanLocationAdapter