from AbsDecayEnvelopeDetectorAdapter import AbsDecayEnvelopeDetectorAdapter
from ManualDetectorAdapter import ManualDetectorAdapter
from WatershedDetectorAdapter import WatershedDetectorAdapter
from AdaptThreshDetectorAdapter import AdaptThreshDetectorAdapter
from GrabCutDetectorAdapter import GrabCutDetectorAdapter
from IntervalMaxMeanDetectorAdapter import IntervalMaxMeanDetectorAdapter
from IntervalPowerSpectrumDetectorAdapter import IntervalPowerSpectrumDetectorAdapter
from IntervalRmsDetectorAdapter import IntervalRmsDetectorAdapter