from MaxFreqParameterAdapter import MaxFreqParameterAdapter
from MinFreqParameterAdapter import MinFreqParameterAdapter
from BandWidthParameterAdapter import BandWidthParameterAdapter
from PeaksAboveParameterAdapter import PeaksAboveParameterAdapter
from PeakFreqParameterAdapter import PeakFreqParameterAdapter